//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_DEPLOYMENT
    {
        public string ID_ { get; set; }
        public string NAME_ { get; set; }
        public string CATEGORY_ { get; set; }
        public string TENANT_ID_ { get; set; }
        public Nullable<System.DateTime> DEPLOY_TIME_ { get; set; }
    }
}
