//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_VARINST
    {
        public string ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string TASK_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string VAR_TYPE_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string BYTEARRAY_ID_ { get; set; }
        public Nullable<double> DOUBLE_ { get; set; }
        public Nullable<decimal> LONG_ { get; set; }
        public string TEXT_ { get; set; }
        public string TEXT2_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_TIME_ { get; set; }
    }
}
