//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RU_EVENT_SUBSCR
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string EVENT_TYPE_ { get; set; }
        public string EVENT_NAME_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string ACTIVITY_ID_ { get; set; }
        public string CONFIGURATION_ { get; set; }
        public System.DateTime CREATED_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string TENANT_ID_ { get; set; }
    }
}
