//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_PROCINST
    {
        public string ID_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string BUSINESS_KEY_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public System.DateTime START_TIME_ { get; set; }
        public Nullable<System.DateTime> END_TIME_ { get; set; }
        public Nullable<decimal> DURATION_ { get; set; }
        public string START_USER_ID_ { get; set; }
        public string START_ACT_ID_ { get; set; }
        public string END_ACT_ID_ { get; set; }
        public string SUPER_PROCESS_INSTANCE_ID_ { get; set; }
        public string DELETE_REASON_ { get; set; }
        public string TENANT_ID_ { get; set; }
        public string NAME_ { get; set; }
    }
}
