//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_RE_MODEL
    {
        public string ID_ { get; set; }
        public Nullable<int> REV_ { get; set; }
        public string NAME_ { get; set; }
        public string KEY_ { get; set; }
        public string CATEGORY_ { get; set; }
        public Nullable<System.DateTime> CREATE_TIME_ { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_TIME_ { get; set; }
        public Nullable<int> VERSION_ { get; set; }
        public string META_INFO_ { get; set; }
        public string DEPLOYMENT_ID_ { get; set; }
        public string EDITOR_SOURCE_VALUE_ID_ { get; set; }
        public string EDITOR_SOURCE_EXTRA_VALUE_ID_ { get; set; }
        public string TENANT_ID_ { get; set; }
    }
}
