//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_HI_TASKINST
    {
        public string ID_ { get; set; }
        public string PROC_DEF_ID_ { get; set; }
        public string TASK_DEF_KEY_ { get; set; }
        public string PROC_INST_ID_ { get; set; }
        public string EXECUTION_ID_ { get; set; }
        public string NAME_ { get; set; }
        public string PARENT_TASK_ID_ { get; set; }
        public string DESCRIPTION_ { get; set; }
        public string OWNER_ { get; set; }
        public string ASSIGNEE_ { get; set; }
        public System.DateTime START_TIME_ { get; set; }
        public Nullable<System.DateTime> CLAIM_TIME_ { get; set; }
        public Nullable<System.DateTime> END_TIME_ { get; set; }
        public Nullable<decimal> DURATION_ { get; set; }
        public string DELETE_REASON_ { get; set; }
        public Nullable<int> PRIORITY_ { get; set; }
        public Nullable<System.DateTime> DUE_DATE_ { get; set; }
        public string FORM_KEY_ { get; set; }
        public string CATEGORY_ { get; set; }
        public string TENANT_ID_ { get; set; }
    }
}
