//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoDetailExportView
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string DPurchaseOrder { get; set; }
        public string OrderCode { get; set; }
        public string OrderType { get; set; }
        public string PartNo { get; set; }
        public string BoStatusName { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public int PartCancelStatus { get; set; }
        public Nullable<int> OrderTypeCode { get; set; }
        public Nullable<int> Status { get; set; }
        public string DealerCode { get; set; }
        public string PartsCode { get; set; }
        public string NameCn { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> EstimateArriveDate { get; set; }
        public string IsCancelStr { get; set; }
        public Nullable<System.DateTime> FixTime { get; set; }
        public Nullable<decimal> ManualAllocation { get; set; }
    }
}
