//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmAuxiliaryBillView
    {
        public long Id { get; set; }
        public string PolicyCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string VehicleTypeCode { get; set; }
        public string VehicleTypeName { get; set; }
        public decimal MaxLevel { get; set; }
        public string Unit { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string CountryName { get; set; }
        public int Status { get; set; }
        public string StatusName { get; set; }
        public string Culture { get; set; }
    }
}
