//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmAutoAudit
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ProductDateFrom { get; set; }
        public Nullable<System.DateTime> ProductDateTo { get; set; }
        public string VehicleType { get; set; }
        public Nullable<int> WarrantyTermFrom { get; set; }
        public Nullable<int> WarrantyTermTo { get; set; }
        public Nullable<decimal> MileageFrom { get; set; }
        public Nullable<decimal> MileageTo { get; set; }
        public string WarrantyType { get; set; }
        public string ApplyType { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CSC { get; set; }
        public string CC { get; set; }
        public bool IsDeleted { get; set; }
        public int Status { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
