//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmAuditPlanWarrantyView
    {
        public Nullable<System.Guid> NId { get; set; }
        public Nullable<long> Num { get; set; }
        public long DealerId { get; set; }
        public long Id { get; set; }
        public Nullable<long> WarrantyId { get; set; }
        public string WarrantyNo { get; set; }
        public Nullable<int> WarrantyCategory { get; set; }
        public Nullable<int> WarrantyType { get; set; }
        public Nullable<int> ApplyType { get; set; }
        public string WorkOrderNo { get; set; }
        public string LicensePlate { get; set; }
        public string VIN { get; set; }
        public string EngineModel { get; set; }
        public Nullable<decimal> TravelMileage { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public string CarModels { get; set; }
        public Nullable<int> CarType { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> WarrantyEnd { get; set; }
        public string AuthorizationKey { get; set; }
        public Nullable<int> AuthorizationType { get; set; }
        public string CSC { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<System.DateTime> RepairStart { get; set; }
        public Nullable<System.DateTime> RepairEnd { get; set; }
        public Nullable<System.DateTime> CloseJob { get; set; }
        public Nullable<int> SaleType { get; set; }
        public Nullable<bool> Is3R { get; set; }
        public Nullable<System.DateTime> PartsSalesDate { get; set; }
        public string SvcActivityCode { get; set; }
        public string SvcAdvisor { get; set; }
        public Nullable<int> RepairReason { get; set; }
        public string DiagnosticCode { get; set; }
        public string FuncGroup { get; set; }
        public Nullable<bool> IsRescue { get; set; }
        public string SupplierNo { get; set; }
        public Nullable<decimal> WorksHoursTotalAmount { get; set; }
        public Nullable<decimal> PartsTotalAmount { get; set; }
        public Nullable<decimal> OthersTotalAmount { get; set; }
        public Nullable<decimal> ApplyTotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> InputOn { get; set; }
        public Nullable<System.DateTime> SubmitOn { get; set; }
        public Nullable<System.DateTime> AuditOn { get; set; }
        public string AuditComments { get; set; }
        public Nullable<bool> IsAttention { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> ReplyWorksHoursTotalAmount { get; set; }
        public Nullable<decimal> ReplyPartsTotalAmount { get; set; }
        public Nullable<decimal> ReplyOthersTotalAmount { get; set; }
        public Nullable<decimal> ReplyApplyTotalAmount { get; set; }
        public Nullable<decimal> TravelMileageEnd { get; set; }
        public Nullable<int> HasRecovery { get; set; }
        public Nullable<int> RepairTime { get; set; }
        public Nullable<int> IsPaid { get; set; }
        public Nullable<int> IsAudited { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public Nullable<System.DateTime> WarrantyAuditOn { get; set; }
        public string TypeName { get; set; }
        public Nullable<byte> AuditStatus { get; set; }
        public string AuditCheatComments { get; set; }
        public Nullable<decimal> CheatCost { get; set; }
        public string Culture { get; set; }
        public Nullable<System.DateTime> CreatePayTime { get; set; }
    }
}
