//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmAuditDealerView
    {
        public long DealerId { get; set; }
        public string DealerName { get; set; }
        public string DealerCode { get; set; }
        public string Currency { get; set; }
        public Nullable<int> AuditType { get; set; }
        public string AuditTypeStr { get; set; }
        public string AuditPriority { get; set; }
        public string Culture { get; set; }
        public Nullable<int> WarrantyCount { get; set; }
        public Nullable<decimal> WarrantyTotalAmount { get; set; }
        public Nullable<System.DateTime> LastAuditDate { get; set; }
        public int AuditedWarrantyCount { get; set; }
        public int AuditedWarrantyTotalAmount { get; set; }
        public Nullable<System.DateTime> UntillDate { get; set; }
    }
}
