//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmAuditReportWarrantyDetailView
    {
        public long PlanId { get; set; }
        public Nullable<long> WarrantyId { get; set; }
        public string WarrantyNo { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public Nullable<decimal> Quanlity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ReplyPercent { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<decimal> CheatCost { get; set; }
        public string Comments { get; set; }
        public Nullable<byte> AuditType { get; set; }
        public string PartTypeName { get; set; }
        public string Culture { get; set; }
        public Nullable<int> PartType { get; set; }
    }
}
