//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmHostOutStock
    {
        public long Id { get; set; }
        public string OuStocktNo { get; set; }
        public decimal OutStockQuantity { get; set; }
        public string OutStockApplyUser { get; set; }
        public string ApplicantContact { get; set; }
        public string ApplicantCompany { get; set; }
        public Nullable<System.DateTime> OutStockDate { get; set; }
        public bool IsDeleted { get; set; }
        public int Status { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string CreatorContact { get; set; }
    }
}
