//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmHostOutStockDetailView
    {
        public long Id { get; set; }
        public long OutStockId { get; set; }
        public int Country { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<long> OldPartId { get; set; }
        public string WarrantyNo { get; set; }
        public string VIN { get; set; }
        public string OldPartNo { get; set; }
        public string OldPartName { get; set; }
        public decimal PartQuantity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public Nullable<System.DateTime> OutStockDate { get; set; }
    }
}
