//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmOldPartStockScrapDetailView
    {
        public long Id { get; set; }
        public string SupplierNo { get; set; }
        public long DealerId { get; set; }
        public string WarrantyNo { get; set; }
        public string VIN { get; set; }
        public bool IsMain { get; set; }
        public string OldPartNo { get; set; }
        public string OldPartName { get; set; }
        public decimal PartQuantity { get; set; }
        public System.DateTime InStoreDate { get; set; }
        public bool IsDeleted { get; set; }
        public string SupplierName { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public Nullable<long> PartsScrapId { get; set; }
    }
}
