//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmPartsReturnBillView
    {
        public long Id { get; set; }
        public string ReturnCode { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string CountryName { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEngName { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleTypeName { get; set; }
        public string CSC { get; set; }
        public string DemandSide { get; set; }
        public string DemandSideName { get; set; }
        public string ReceivingParty { get; set; }
        public string ReceivingPartyName { get; set; }
        public string ReturnReason { get; set; }
        public string ReturnReasonName { get; set; }
        public string ReturnType { get; set; }
        public string ReturnTypeName { get; set; }
        public System.DateTime ReturnValidityPeriodFrom { get; set; }
        public Nullable<System.DateTime> ReturnValidityPeriodTo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<System.DateTime> ProductionDateFrom { get; set; }
        public Nullable<System.DateTime> ProductionDateTo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int IsValid { get; set; }
        public string Culture { get; set; }
    }
}
