//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmPrepRecoveryDetailView
    {
        public Nullable<long> Id { get; set; }
        public string SupplierRecoveryCode { get; set; }
        public long WarrantyId { get; set; }
        public Nullable<decimal> ReplyWorksHoursTotalAmount { get; set; }
        public Nullable<decimal> ReplyPartsTotalAmount { get; set; }
        public Nullable<decimal> ReplyOtherTotalAmount { get; set; }
        public Nullable<decimal> ReplyApplyTotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> SupplierAmount { get; set; }
        public Nullable<decimal> SupplierPercent { get; set; }
        public Nullable<decimal> FactoryPercent { get; set; }
        public Nullable<decimal> DesignPercent { get; set; }
        public Nullable<decimal> DealerPercent { get; set; }
        public Nullable<decimal> NTFPercent { get; set; }
        public Nullable<decimal> OtherPercent { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CSC { get; set; }
        public int CC { get; set; }
        public Nullable<System.DateTime> InputOn { get; set; }
        public Nullable<System.DateTime> RepairEnd { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string WarrantyTypeStr { get; set; }
        public string Deviation { get; set; }
        public string Culture { get; set; }
        public Nullable<long> CountryId { get; set; }
        public string Country { get; set; }
        public string WorkCode { get; set; }
        public string WorkRemark { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string OldPartNo { get; set; }
        public string OldPartName { get; set; }
        public string WarrantyNo { get; set; }
        public string VIN { get; set; }
        public Nullable<decimal> TravelMileageEnd { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public int WarrantyType { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEngName { get; set; }
        public Nullable<int> RecoveryStatus { get; set; }
        public string ClaimType { get; set; }
        public int IsPaid { get; set; }
        public int HasRecovery { get; set; }
    }
}
