//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmPayToDealerList
    {
        public long Id { get; set; }
        public string PayMonth { get; set; }
        public string PayNo { get; set; }
        public long DealerId { get; set; }
        public decimal TotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> PDI { get; set; }
        public Nullable<decimal> FirstInsurance { get; set; }
        public Nullable<decimal> Guarantee { get; set; }
        public Nullable<decimal> Other { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
        public string Comments { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public decimal Tax { get; set; }
        public decimal TotalNoTax { get; set; }
        public int PaymentType { get; set; }
        public Nullable<long> AuditBy { get; set; }
        public decimal TariffRate { get; set; }
    }
}
