//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmPayToDealer
    {
        public long Id { get; set; }
        public long PayId { get; set; }
        public long WarrantyId { get; set; }
        public int CostType { get; set; }
        public string VIN { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal ReplyQuantity { get; set; }
        public decimal ReplyUnitPrice { get; set; }
        public decimal ReplyRate { get; set; }
        public Nullable<decimal> PartsHandingCosts { get; set; }
        public Nullable<decimal> ReplyTotalAmount { get; set; }
        public string Currency { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public long CostId { get; set; }
        public Nullable<int> WarrantyCategory { get; set; }
        public int PayType { get; set; }
        public string Comments { get; set; }
        public int PaymentType { get; set; }
    }
}
