//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmPartsCost
    {
        public long Id { get; set; }
        public long WarrantyId { get; set; }
        public bool IsMain { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string OldPartNo { get; set; }
        public string OldPartName { get; set; }
        public decimal Quanlity { get; set; }
        public decimal Price { get; set; }
        public decimal Percents { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ReplyQuanlity { get; set; }
        public Nullable<decimal> ReplyPrice { get; set; }
        public Nullable<decimal> PartsHandingCosts { get; set; }
        public Nullable<decimal> ReplyPercent { get; set; }
        public Nullable<decimal> ReplyTotalAmount { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public int HasReturned { get; set; }
        public int ReturnNoticeStatus { get; set; }
        public int HasReplied { get; set; }
        public int StockType { get; set; }
        public int StockStatus { get; set; }
        public Nullable<decimal> RestQuantity { get; set; }
        public string NewPartSerialNumber { get; set; }
        public string OldPartSerialNumber { get; set; }
        public string PartCheckResult { get; set; }
        public decimal SupplierPercents { get; set; }
        public decimal CustomerPercents { get; set; }
        public decimal ReplySupplierPercents { get; set; }
        public decimal ReplyCustomerPercents { get; set; }
    }
}
