//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmReverseDebitView
    {
        public long Id { get; set; }
        public bool IsDebited { get; set; }
        public Nullable<long> WarrantyId { get; set; }
        public string WarrantyNo { get; set; }
        public int CostType { get; set; }
        public string CostTypeName { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public Nullable<decimal> PartQuantity { get; set; }
        public Nullable<decimal> ReplyQuanlity { get; set; }
        public Nullable<decimal> ReplyPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string DebitProportion { get; set; }
        public Nullable<decimal> GoodsReceiptDebitAmount { get; set; }
        public Nullable<int> DebitReason { get; set; }
        public Nullable<decimal> RKReceiptDebitAmount { get; set; }
        public string RKDebitProportion { get; set; }
        public string RKDebitReason { get; set; }
        public Nullable<decimal> LogisticsDebit { get; set; }
        public Nullable<System.DateTime> DebitDatetime { get; set; }
        public Nullable<int> DebitType { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> ActualGoodsReceiptQuantity { get; set; }
        public bool IsDeleted { get; set; }
        public string Culture { get; set; }
    }
}
