//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmUnionOldPartsView
    {
        public Nullable<long> WarrantyId { get; set; }
        public Nullable<int> WarrantyType { get; set; }
        public string WarrantyNo { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ReturnType { get; set; }
        public int StockType { get; set; }
        public string SupplierNo { get; set; }
        public long DealerId { get; set; }
        public Nullable<int> StockStatus { get; set; }
        public Nullable<System.DateTime> RepairStart { get; set; }
        public Nullable<System.DateTime> CloseJob { get; set; }
        public string CSC { get; set; }
        public Nullable<bool> IsMain { get; set; }
    }
}
