//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmWarrantyAndPartsView
    {
        public string WarrantyNo { get; set; }
        public string VinCode { get; set; }
        public string CSC { get; set; }
        public Nullable<System.DateTime> RepairStart { get; set; }
        public Nullable<System.DateTime> RepairEnd { get; set; }
        public Nullable<int> RepairDays { get; set; }
        public Nullable<System.DateTime> Salesdate { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string MasterPartNo { get; set; }
        public Nullable<long> AlarmId { get; set; }
        public Nullable<int> CurrentType { get; set; }
        public Nullable<int> IsNeedShow { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public long ThreeGuaranteeId { get; set; }
        public int AlarmCount { get; set; }
    }
}
