//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmWarrantyPeriodSettingView
    {
        public long Id { get; set; }
        public string PolicyCode { get; set; }
        public long CountryId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public string VehicleTypeCode { get; set; }
        public string VehicleModelName { get; set; }
        public int CarType { get; set; }
        public int WarrantyType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public decimal WarrantyPeriod { get; set; }
        public decimal Mileage { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CarTypeName { get; set; }
        public string Culture { get; set; }
        public string WarrantyTypeName { get; set; }
        public string CountryName { get; set; }
        public string AreaName { get; set; }
        public string StatusName { get; set; }
    }
}
