//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmWarrantyView
    {
        public long Id { get; set; }
        public long WarrantyId { get; set; }
        public string WarrantyNo { get; set; }
        public int WarrantyCategory { get; set; }
        public int WarrantyType { get; set; }
        public string WarrantyTypeName { get; set; }
        public int ApplyType { get; set; }
        public string ApplyTypeName { get; set; }
        public long DealerId { get; set; }
        public string WorkOrderNo { get; set; }
        public string LicensePlate { get; set; }
        public string VIN { get; set; }
        public string EngineModel { get; set; }
        public Nullable<decimal> TravelMileage { get; set; }
        public Nullable<decimal> TravelMileageEnd { get; set; }
        public System.DateTime ManufactureDate { get; set; }
        public string CarModels { get; set; }
        public string VehicleTypeCode { get; set; }
        public string VehicleTypeName { get; set; }
        public int CarType { get; set; }
        public string CarTypeName { get; set; }
        public Nullable<System.DateTime> WarrantyStart { get; set; }
        public Nullable<System.DateTime> WarrantyEnd { get; set; }
        public string AuthorizationKey { get; set; }
        public Nullable<int> AuthorizationType { get; set; }
        public string CSC { get; set; }
        public int CC { get; set; }
        public Nullable<System.DateTime> RepairStart { get; set; }
        public Nullable<System.DateTime> RepairEnd { get; set; }
        public Nullable<System.DateTime> CloseJob { get; set; }
        public Nullable<int> SaleType { get; set; }
        public bool Is3R { get; set; }
        public string Is3RName { get; set; }
        public Nullable<System.DateTime> PartsSalesDate { get; set; }
        public string SvcActivityCode { get; set; }
        public string SvcAdvisor { get; set; }
        public Nullable<int> RepairReason { get; set; }
        public string DiagnosticCode { get; set; }
        public string FuncGroup { get; set; }
        public string FuncGroupDesc { get; set; }
        public bool IsRescue { get; set; }
        public string IsRescueName { get; set; }
        public string SupplierNo { get; set; }
        public Nullable<decimal> WorksHoursTotalAmount { get; set; }
        public Nullable<decimal> PartsTotalAmount { get; set; }
        public Nullable<decimal> OthersTotalAmount { get; set; }
        public Nullable<decimal> ApplyTotalAmount { get; set; }
        public Nullable<decimal> ReplyWorksHoursTotalAmount { get; set; }
        public Nullable<decimal> ExportReplyWorksHoursTotalAmount { get; set; }
        public Nullable<decimal> ReplyPartsTotalAmount { get; set; }
        public Nullable<decimal> ExportReplyPartsTotalAmount { get; set; }
        public Nullable<decimal> ReplyOthersTotalAmount { get; set; }
        public Nullable<decimal> ExportReplyOthersTotalAmount { get; set; }
        public Nullable<decimal> ReplyApplyTotalAmount { get; set; }
        public Nullable<decimal> ExportReplyApplyTotalAmount { get; set; }
        public string Currency { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<System.DateTime> InputOn { get; set; }
        public Nullable<System.DateTime> SubmitOn { get; set; }
        public Nullable<System.DateTime> AuditOn { get; set; }
        public string AuditComments { get; set; }
        public bool IsAttention { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string CustName { get; set; }
        public string CustAddress { get; set; }
        public string CustPhone { get; set; }
        public int HasCreatedPay { get; set; }
        public int IsPaid { get; set; }
        public string IsPaidStr { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
        public long CampaignRepairPackageId { get; set; }
        public int PreAuthorizationIsUsed { get; set; }
        public Nullable<System.DateTime> PreAuthorizationUsedOn { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public Nullable<long> ProvinceId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public string DealerAreaName { get; set; }
        public string WarrantyTypeStr { get; set; }
        public string WarrantyStatusStr { get; set; }
        public string AuthorizationTypeStr { get; set; }
        public string RepairReasonStr { get; set; }
        public string Deviation { get; set; }
        public string CSCName { get; set; }
        public string Culture { get; set; }
        public string SupplierName { get; set; }
        public string SupplierEngName { get; set; }
        public string PartNo { get; set; }
        public string PartName { get; set; }
        public string OldPartNo { get; set; }
        public string OldPartName { get; set; }
        public Nullable<decimal> ReplyQuanlity { get; set; }
        public Nullable<decimal> Quanlity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PartReplayPrice { get; set; }
        public Nullable<decimal> ExportPartReplayPrice { get; set; }
        public string SupplierRecoveryCode { get; set; }
        public Nullable<int> ClaimsStatus { get; set; }
        public string ClaimsStatusStr { get; set; }
        public Nullable<int> HasReturned { get; set; }
        public string HasReturnedName { get; set; }
        public string PrintStatus { get; set; }
        public string PrintStatusName { get; set; }
        public string AttachUploadId { get; set; }
        public string CampaignCode { get; set; }
        public string CampaignDescription { get; set; }
        public string CCName { get; set; }
        public string CCNameEng { get; set; }
        public string WarrantyCategoryStr { get; set; }
        public int IsLocked { get; set; }
        public string IsLockedName { get; set; }
        public string FaultSymptom { get; set; }
        public string FaultDiagnosis { get; set; }
        public string SolutionResult { get; set; }
        public string DealerRemarks { get; set; }
        public string ManufactureRemarks { get; set; }
        public string FaultSymptom1 { get; set; }
        public string FaultDiagnosis1 { get; set; }
        public string SolutionResult1 { get; set; }
        public string DealerRemarks1 { get; set; }
        public string ManufactureRemarks1 { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string CountryName { get; set; }
        public string DealerCountryCode { get; set; }
        public string ProvinceName { get; set; }
        public string CityName { get; set; }
        public string CampaignRepairPackageCode { get; set; }
        public int IsManualCreate { get; set; }
        public string WorkCode { get; set; }
        public string WorkRemark { get; set; }
        public Nullable<decimal> WorkHours { get; set; }
        public Nullable<decimal> WorkPrice { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> ExportWorkReplayPrice { get; set; }
        public Nullable<decimal> PReplyWorksHoursTotalAmount { get; set; }
        public Nullable<decimal> PReplyPartsTotalAmount { get; set; }
        public Nullable<decimal> PReplyOtherTotalAmount { get; set; }
        public Nullable<decimal> PReplyApplyTotalAmount { get; set; }
        public string HasCreatedPayStr { get; set; }
        public Nullable<System.DateTime> CreatePayTime { get; set; }
        public string PssCode { get; set; }
        public string VehicleYear { get; set; }
        public string RepairPackageName { get; set; }
    }
}
