//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClmWarrantyPeriodSettingWithCountryCodeView
    {
        public decimal WarrantyPeriod { get; set; }
        public decimal Mileage { get; set; }
        public string CountryCode { get; set; }
        public string VehicleTypeCode { get; set; }
        public int CarType { get; set; }
    }
}
