//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrCaseAllV
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Question { get; set; }
        public string DealerQuestion { get; set; }
        public Nullable<System.DateTime> ComplaintDistributionTime { get; set; }
        public Nullable<System.DateTime> DealerReceiveTime { get; set; }
        public Nullable<System.DateTime> ExpectedEndDate { get; set; }
        public string CaseSolution { get; set; }
        public Nullable<System.DateTime> ComplaintCloseTime { get; set; }
        public string OrgName { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerTel { get; set; }
        public string CreatedByName { get; set; }
        public string Channel { get; set; }
        public string ComplaintLevel { get; set; }
        public Nullable<long> DealerId { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string ShortName { get; set; }
        public string ShopAddress { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string DealerStates { get; set; }
        public Nullable<long> Contact { get; set; }
        public string ContactPhone { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public string MobilePhone { get; set; }
        public string Vin { get; set; }
        public string Licenseno { get; set; }
        public string Enginenumber { get; set; }
        public Nullable<System.DateTime> Guaranteestartdate { get; set; }
        public Nullable<System.DateTime> Salesdate { get; set; }
        public string VehicleTypeName { get; set; }
        public string CarProperty { get; set; }
        public string CaseLevel1Name { get; set; }
        public string CaseLevel2Name { get; set; }
        public string CaseLevel3Name { get; set; }
        public string CaseLevel4Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
    }
}
