//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrCallCenterContactActivity
    {
        public long Id { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string Name { get; set; }
        public Nullable<long> CallcenterContactActivity { get; set; }
        public Nullable<int> Channel { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<long> Contact { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Satisfactory { get; set; }
        public Nullable<int> Type { get; set; }
        public string UpdateKey { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Commons { get; set; }
        public long CreatedBy { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<int> ContactStatus { get; set; }
    }
}
