//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerArchiveView
    {
        public long Id { get; set; }
        public string VinCode { get; set; }
        public string Plate { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string CustomerName { get; set; }
        public string MobilePhone { get; set; }
        public string Sender { get; set; }
        public string SenderTel { get; set; }
        public string VehicleName { get; set; }
        public string DealerName { get; set; }
        public string CityName { get; set; }
        public string ProvinceName { get; set; }
        public string CountryName { get; set; }
        public string SmallRegionName { get; set; }
        public string BigRegionName { get; set; }
        public string ServiceTypeName { get; set; }
        public string SpCode { get; set; }
        public string NameCn { get; set; }
        public string MaterialTypeName { get; set; }
        public Nullable<decimal> NeedCount { get; set; }
        public Nullable<decimal> UseCount { get; set; }
        public Nullable<System.DateTime> ReceiveAt { get; set; }
        public string IntoStoreYear { get; set; }
        public string IntoStoreYearQuarter { get; set; }
        public string IntoStoreYearMonth { get; set; }
        public string IntoStoreYearMonthDay { get; set; }
    }
}
