//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCarView
    {
        public string CityName { get; set; }
        public string ProvinceName { get; set; }
        public string CountryName { get; set; }
        public string SmallRegionName { get; set; }
        public string BigRegionName { get; set; }
        public string DealerCode { get; set; }
        public string ShortName { get; set; }
        public long SvcVehicleDeliveryId { get; set; }
        public string VehicleType { get; set; }
        public string VinCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Year { get; set; }
        public string YearMonth { get; set; }
        public string YearMD { get; set; }
        public string YearQuarter { get; set; }
    }
}
