//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspDealerEmployeeView
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long accountid { get; set; }
        public Nullable<long> orgid { get; set; }
        public string empno { get; set; }
        public string name { get; set; }
        public string dealerCode { get; set; }
        public Nullable<long> dealerId { get; set; }
        public string shortName { get; set; }
        public string fullName { get; set; }
        public string displayName { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string avatarUrl { get; set; }
        public string postids { get; set; }
        public string postnames { get; set; }
        public string roleids { get; set; }
        public string rolenames { get; set; }
        public string rolecodes { get; set; }
    }
}
