//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspDealerEmployeePostView
    {
        public long id { get; set; }
        public long userid { get; set; }
        public long accountid { get; set; }
        public Nullable<long> orgid { get; set; }
        public string empno { get; set; }
        public string name { get; set; }
        public string dealerCode { get; set; }
        public string displayName { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public long postId { get; set; }
        public string postname { get; set; }
    }
}
