//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspImportPart
    {
        public long Id { get; set; }
        public string Source { get; set; }
        public string SpCode { get; set; }
        public string SpName { get; set; }
        public decimal Q { get; set; }
        public Nullable<int> InstallTimes { get; set; }
        public string VinCode { get; set; }
        public string EngineCode { get; set; }
        public string PlateCode { get; set; }
        public string CustomerId { get; set; }
        public string CustomerPhone { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
