//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspSaleReturn
    {
        public long Id { get; set; }
        public string SaleReturnCode { get; set; }
        public string SaleCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ReturnDt { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string PlateNumber { get; set; }
        public string VinCode { get; set; }
        public Nullable<decimal> ShouldA { get; set; }
        public string DealerName { get; set; }
        public string DealerId { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string SaleSettleCode { get; set; }
        public Nullable<System.DateTime> SettleDt { get; set; }
        public Nullable<int> SettleBy { get; set; }
        public Nullable<decimal> ReceiveA { get; set; }
        public Nullable<bool> ComplateFlag { get; set; }
        public Nullable<int> SettleStyle { get; set; }
    }
}
