//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspTransfer
    {
        public long Id { get; set; }
        public string TransferCode { get; set; }
        public Nullable<int> Type { get; set; }
        public string ApplyBy { get; set; }
        public string ApplyCode { get; set; }
        public string ApplyName { get; set; }
        public string ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public string Address { get; set; }
        public string Receiver { get; set; }
        public string Mobile { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<int> Cate { get; set; }
        public string TransferInCode { get; set; }
    }
}
