//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspTransferExportView
    {
        public long Id { get; set; }
        public string TransferCode { get; set; }
        public string TransferInCode { get; set; }
        public string DealerName { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> PartCount { get; set; }
        public Nullable<decimal> TotalQuantity { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string StatusName { get; set; }
        public string TypeName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Cate { get; set; }
        public string DealerId { get; set; }
        public string ServiceCode { get; set; }
        public string SpCode { get; set; }
        public string SpName { get; set; }
        public string ToWarehouseCode { get; set; }
        public string ToStorageCode { get; set; }
        public Nullable<decimal> Q { get; set; }
        public Nullable<decimal> P { get; set; }
        public Nullable<decimal> A { get; set; }
    }
}
