//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DspWrongView
    {
        public long Id { get; set; }
        public string WrongCode { get; set; }
        public string PurchaseOrderCode { get; set; }
        public string DeliveryOrderId { get; set; }
        public string ShipmentOrderId { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public Nullable<int> Style { get; set; }
        public Nullable<int> Status { get; set; }
        public string StockInCode { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> DealWay { get; set; }
        public string Contacter { get; set; }
        public string Tel { get; set; }
        public Nullable<int> DetailCount { get; set; }
        public Nullable<int> AttachCount { get; set; }
        public string StyleName { get; set; }
        public string DealWayName { get; set; }
        public string StatusName { get; set; }
        public string Comments { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
    }
}
