//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fr_schedulerecord
    {
        public int ID { get; set; }
        public string tname { get; set; }
        public string sinfo { get; set; }
        public Nullable<short> type { get; set; }
        public string msg { get; set; }
        public string trace { get; set; }
        public Nullable<System.DateTime> logtime { get; set; }
        public string detailmsg { get; set; }
    }
}
