//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FR_SCHEDULE_ACTIONLIST
    {
        public int id { get; set; }
        public Nullable<int> emailId { get; set; }
        public Nullable<int> ftpId { get; set; }
        public Nullable<int> printId { get; set; }
        public Nullable<int> classId { get; set; }
        public Nullable<int> pushId { get; set; }
        public Nullable<int> smsId { get; set; }
        public Nullable<int> messageId { get; set; }
        public string extraOutputFileActions { get; set; }
    }
}
