//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GdOrderItem
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> PurchaserId { get; set; }
        public Nullable<long> ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Image { get; set; }
        public Nullable<long> SkuId { get; set; }
        public string SkuCode { get; set; }
        public Nullable<int> SkuPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Attriute { get; set; }
        public Nullable<int> ShipFee { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsMaster { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
