//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GdRetailOrder
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> OuterId { get; set; }
        public Nullable<long> PurchaserId { get; set; }
        public string PurchaserName { get; set; }
        public string PurchaserMobile { get; set; }
        public Nullable<long> ShopId { get; set; }
        public string ShopName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> OriginFee { get; set; }
        public Nullable<int> ShipFee { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Fee { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<int> IsValid { get; set; }
    }
}
