//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GdStock
    {
        public long Id { get; set; }
        public string SkuCode { get; set; }
        public long ItemId { get; set; }
        public string Model { get; set; }
        public string OuterId { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string attrs { get; set; }
        public long AvailableQuantity { get; set; }
        public Nullable<long> LockedQuantity { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
