//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geely_wsorderBase_20180420
    {
        public System.Guid geely_wsorderId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public System.Guid OwnerId { get; set; }
        public int OwnerIdType { get; set; }
        public Nullable<System.Guid> OwningBusinessUnit { get; set; }
        public int statecode { get; set; }
        public Nullable<int> statuscode { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<int> ImportSequenceNumber { get; set; }
        public Nullable<System.DateTime> OverriddenCreatedOn { get; set; }
        public Nullable<int> TimeZoneRuleVersionNumber { get; set; }
        public Nullable<int> UTCConversionTimeZoneCode { get; set; }
        public string geely_wsordercode { get; set; }
        public Nullable<System.Guid> processid { get; set; }
        public Nullable<System.Guid> stageid { get; set; }
        public string traversedpath { get; set; }
        public Nullable<System.Guid> geely_brand { get; set; }
        public Nullable<System.Guid> geely_carmaterialid { get; set; }
        public Nullable<System.Guid> geely_carstockid { get; set; }
        public Nullable<System.Guid> geely_dealer { get; set; }
        public Nullable<System.Guid> geely_dealerwarehouse { get; set; }
        public string geely_deliverytime { get; set; }
        public Nullable<System.DateTime> geely_expecteddate { get; set; }
        public Nullable<int> geely_financereview { get; set; }
        public Nullable<int> geely_from { get; set; }
        public Nullable<bool> geely_isgoodscar { get; set; }
        public Nullable<bool> geely_isshowcar { get; set; }
        public Nullable<bool> geely_istrycar { get; set; }
        public string geely_lockreason { get; set; }
        public Nullable<bool> geely_lockstatus { get; set; }
        public Nullable<System.DateTime> geely_locktime { get; set; }
        public Nullable<int> geely_mdmid { get; set; }
        public Nullable<System.Guid> geely_oemplace { get; set; }
        public Nullable<int> geely_orderpriority { get; set; }
        public Nullable<int> geely_orderreview { get; set; }
        public Nullable<int> geely_orderstatus { get; set; }
        public string geely_payer { get; set; }
        public Nullable<System.Guid> geely_period { get; set; }
        public Nullable<int> geely_priority { get; set; }
        public Nullable<System.Guid> geely_relatedretailorder { get; set; }
        public Nullable<int> geely_salesapproval { get; set; }
        public string geely_shiptoparty { get; set; }
        public Nullable<int> geely_testorofficialcar { get; set; }
        public string geely_updatekey { get; set; }
        public Nullable<System.Guid> geely_vehiclecolor { get; set; }
        public Nullable<System.Guid> geely_vehicleconfiguration { get; set; }
        public Nullable<System.Guid> geely_vehicledisplacement { get; set; }
        public Nullable<System.Guid> geely_vehicleinfoid { get; set; }
        public Nullable<System.Guid> geely_vehicletype { get; set; }
        public Nullable<System.Guid> geely_vehicleuse { get; set; }
        public Nullable<System.DateTime> geely_wsorderdate { get; set; }
        public Nullable<int> geely_wsordertype { get; set; }
        public Nullable<System.Guid> geely_vehicleprofileid { get; set; }
        public Nullable<decimal> geely_awarddeduct { get; set; }
        public Nullable<System.Guid> TransactionCurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> geely_awarddeduct_Base { get; set; }
        public Nullable<System.Guid> geely_bank { get; set; }
        public string geely_bankacceptance { get; set; }
        public Nullable<int> geely_capitaltype { get; set; }
        public Nullable<System.Guid> geely_dealerplanid { get; set; }
        public Nullable<int> geely_financereviewtype { get; set; }
        public Nullable<decimal> geely_listprice { get; set; }
        public Nullable<decimal> geely_listprice_Base { get; set; }
        public Nullable<decimal> geely_locationsalesaward { get; set; }
        public Nullable<decimal> geely_locationsalesaward_Base { get; set; }
        public Nullable<System.DateTime> geely_orderreviewdate { get; set; }
        public Nullable<System.DateTime> geely_receiptdate { get; set; }
        public Nullable<System.DateTime> geely_settlementdate { get; set; }
        public Nullable<decimal> geely_settlementprice { get; set; }
        public Nullable<decimal> geely_settlementprice_Base { get; set; }
        public Nullable<int> geely_settlementpriority { get; set; }
        public string geely_shippinginstruction { get; set; }
        public Nullable<int> geely_soreviewstatus { get; set; }
        public Nullable<int> geely_soshiptocheck { get; set; }
        public Nullable<decimal> geely_vehiclediscount { get; set; }
        public Nullable<decimal> geely_vehiclediscount_Base { get; set; }
        public string geely_remark { get; set; }
        public string geely_sapcode { get; set; }
        public string geely_sapcon { get; set; }
        public Nullable<System.DateTime> geely_instocktime { get; set; }
        public Nullable<bool> geely_ishold { get; set; }
        public Nullable<int> geely_sopricecheck { get; set; }
        public string geely_week { get; set; }
        public string geely_approvereason { get; set; }
    }
}
