//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportTaskTypeView
    {
        public Nullable<long> Num { get; set; }
        public long TaskTypeId { get; set; }
        public string TaskTypeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Month { get; set; }
        public Nullable<int> MonthNumber { get; set; }
        public Nullable<int> EndMonthNumber { get; set; }
        public string DealerName { get; set; }
        public long DealerId { get; set; }
        public Nullable<int> IsRequired { get; set; }
        public Nullable<long> AreaId { get; set; }
        public Nullable<long> QyddUserId { get; set; }
    }
}
