//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainPartsSubPartView
    {
        public long Id { get; set; }
        public string PartsCode { get; set; }
        public string NameCn { get; set; }
        public string SonCode { get; set; }
        public string SonName { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> TotalMQty { get; set; }
    }
}
