//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmCostCenter
    {
        public Nullable<long> OrgId { get; set; }
        public string OrgName { get; set; }
        public Nullable<decimal> ITEM { get; set; }
        public string KOSTL { get; set; }
        public string KOSAR { get; set; }
        public string KTEXT { get; set; }
        public string ACTION { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public int Id { get; set; }
    }
}
