//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmDealerBelongView
    {
        public long Id { get; set; }
        public string DealerCode { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string BigAreaName { get; set; }
        public long BigAreaId { get; set; }
        public string SmalAreaName { get; set; }
        public long SmalAreaId { get; set; }
        public string CityName { get; set; }
        public long CityId { get; set; }
        public string ProvinceName { get; set; }
        public long ProvinceId { get; set; }
        public string CountryName { get; set; }
        public long CountryId { get; set; }
    }
}
