//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmDealerView_Fitch
    {
        public long Id { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string DealerCode { get; set; }
        public string SalePhone { get; set; }
        public string ServicePhone { get; set; }
        public string ShopAddress { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public string ProvinceCode { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> DealerStates { get; set; }
    }
}
