//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmPost
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public long OrgId { get; set; }
        public Nullable<bool> IsInterview { get; set; }
        public Nullable<bool> IsTraining { get; set; }
        public Nullable<bool> IsPartTime { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<int> EmployNumber { get; set; }
        public Nullable<int> EmployType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
