//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmPartsForPartECommerceView
    {
        public string materialNo { get; set; }
        public string name { get; set; }
        public string categoryName { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> height { get; set; }
        public string location { get; set; }
        public string supportVehicleType { get; set; }
        public Nullable<bool> isEnableSale { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
