//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MdmSupplierPurchasePriceView
    {
        public Nullable<long> IdentityId { get; set; }
        public Nullable<long> RN { get; set; }
        public string PartNo { get; set; }
        public string CompanyNo { get; set; }
        public string SupplierNo { get; set; }
        public string WmNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ContractNo { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal PriceUnit { get; set; }
        public string Currency { get; set; }
        public string SpecialPurchaseType { get; set; }
    }
}
