//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatusLog
    {
        public long ID { get; set; }
        public string Category { get; set; }
        public string OrderNO { get; set; }
        public string SourceOrderNO { get; set; }
        public Nullable<int> StatusFrom { get; set; }
        public Nullable<int> StatusTo { get; set; }
        public string LogType { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    }
}
