//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_TRIGGERS
    {
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public string IS_VOLATILE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> NEXT_FIRE_TIME { get; set; }
        public Nullable<decimal> PREV_FIRE_TIME { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string TRIGGER_STATE { get; set; }
        public string TRIGGER_TYPE { get; set; }
        public decimal START_TIME { get; set; }
        public Nullable<decimal> END_TIME { get; set; }
        public string CALENDAR_NAME { get; set; }
        public Nullable<short> MISFIRE_INSTR { get; set; }
        public byte[] JOB_DATA { get; set; }
    }
}
