//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOrderSimpleCount
    {
        public long Id { get; set; }
        public Nullable<long> VehicleTypeId { get; set; }
        public int CountType { get; set; }
        public System.DateTime CountDate { get; set; }
        public int TotalCount { get; set; }
        public int YearCount { get; set; }
        public int MomthCount { get; set; }
        public int DayCount { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
