//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RgmInspectView
    {
        public Nullable<decimal> Num { get; set; }
        public string TopItem { get; set; }
        public string MainItem { get; set; }
        public string SubItem { get; set; }
        public string LastItem { get; set; }
        public long Id { get; set; }
        public long InspectTaskId { get; set; }
        public Nullable<double> Score { get; set; }
        public string ScoreStandard { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comments { get; set; }
    }
}
