//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RgmInspectPlanTaskType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RgmInspectPlanTaskType()
        {
            this.RgmInspectTaskTypeMaterials = new HashSet<RgmInspectTaskTypeMaterial>();
        }
    
        public long Id { get; set; }
        public long InspectPlanId { get; set; }
        public long InspectTaskTypeId { get; set; }
        public long DealerId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> FirstReminder { get; set; }
        public Nullable<int> SecondReminder { get; set; }
        public Nullable<byte> ReportStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> DealerVisible { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<bool> DealerReportVisible { get; set; }
        public string Address { get; set; }
    
        public virtual RgmInspectPlan RgmInspectPlan { get; set; }
        public virtual RgmInspectTaskType RgmInspectTaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RgmInspectTaskTypeMaterial> RgmInspectTaskTypeMaterials { get; set; }
    }
}
