//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RgmImprovmentTempView
    {
        public long Id { get; set; }
        public Nullable<long> InspectId { get; set; }
        public long DealerId { get; set; }
        public string ImprovementItem { get; set; }
        public int ModuleType { get; set; }
        public Nullable<long> CrCaseId { get; set; }
        public Nullable<long> InspectParentId { get; set; }
        public long PlanTaskTypeId { get; set; }
        public string Comments { get; set; }
        public string DocumentUrl { get; set; }
        public int Tips { get; set; }
    }
}
