//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RgmPickFromImprovementItemBaseView
    {
        public long Id { get; set; }
        public long TaskTypeId { get; set; }
        public string TaskName { get; set; }
        public long TaskId { get; set; }
        public string InspectItem { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<long> BaseId { get; set; }
        public string ImprovementItem { get; set; }
    }
}
