//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmCompanyView
    {
        public long Id { get; set; }
        public string CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public string NickCompanyName { get; set; }
        public string CompanyOwner { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Comments { get; set; }
        public string UserName { get; set; }
        public bool IsDeleted { get; set; }
    }
}
