//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmDiffanalyseReportsDetail
    {
        public long Id { get; set; }
        public long ReportId { get; set; }
        public string PartNo { get; set; }
        public string PartCname { get; set; }
        public string PartEname { get; set; }
        public string PartType { get; set; }
        public string Dloc { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<decimal> RealCount { get; set; }
        public Nullable<decimal> DiffNum { get; set; }
        public string DiffReason { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string ZoneNo { get; set; }
        public Nullable<decimal> LossNum { get; set; }
        public Nullable<decimal> FreezeCount { get; set; }
        public Nullable<decimal> AllocateNum { get; set; }
        public Nullable<decimal> AvaliableStocks { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SupplierNum { get; set; }
        public Nullable<decimal> ProfitNum { get; set; }
    }
}
