//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmEntrustOrder
    {
        public long Id { get; set; }
        public string OutsideCommissionedCode { get; set; }
        public string CompanyCode { get; set; }
        public string WmNo { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string OrderNum { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public int HasSRMRecived { get; set; }
        public Nullable<System.DateTime> SRMRecivedOn { get; set; }
        public Nullable<System.DateTime> ETAOn { get; set; }
        public bool SAPCreated { get; set; }
        public Nullable<int> GenPickUpStatus { get; set; }
        public bool HasSRMConfirm { get; set; }
        public Nullable<System.DateTime> SRMConfirmDate { get; set; }
        public bool IsEmergency { get; set; }
        public string ApiType { get; set; }
    }
}
