//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmMaterialOrderGenView
    {
        public string PartsCode { get; set; }
        public string NameCn { get; set; }
        public string Specification { get; set; }
        public string PartUnits { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal Quota { get; set; }
        public string SupplierNo { get; set; }
        public Nullable<long> PartsBomGroupId { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<long> ChildId { get; set; }
        public string ContractCompanyNo { get; set; }
        public string ContractWmNo { get; set; }
        public string QuotaCompanyNo { get; set; }
        public string QuotaWmNo { get; set; }
        public string ParentPartNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    }
}
