//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmOemOutputPrintPartsView
    {
        public string OEMOutOrderCode { get; set; }
        public string ShippingOrderCode { get; set; }
        public string SONo { get; set; }
        public string DealerName { get; set; }
        public string DealerCode { get; set; }
        public string PartsCode { get; set; }
        public string NameCn { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> DemandQuantity { get; set; }
        public string BoxNum { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int BoxType { get; set; }
        public string OrderType { get; set; }
    }
}
