//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmOrderCalendarWithWarehouseView
    {
        public long Id { get; set; }
        public string DealerNum { get; set; }
        public string DealerName { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string ProcessTime1 { get; set; }
        public string ProcessTime2 { get; set; }
        public string GreenOrderStopTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
