//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmOemOutOrderDetailView
    {
        public long Id { get; set; }
        public string OEMOutOrderCode { get; set; }
        public string BoxNum { get; set; }
        public string POCode { get; set; }
        public string SONo { get; set; }
        public Nullable<decimal> PartQuantity { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsDeleted { get; set; }
    }
}
