//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmOutVolView
    {
        public long Id { get; set; }
        public string POCode { get; set; }
        public string SONo { get; set; }
        public string DealerCode { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> PoType { get; set; }
        public string SupplyCycle { get; set; }
        public string SupplyMorning { get; set; }
        public string SupplyAfterNoon { get; set; }
        public string PoTypeName { get; set; }
        public string LineCode { get; set; }
        public string LineName { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public Nullable<decimal> CNum { get; set; }
        public string CType { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
    }
}
