//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPartsPickCardView
    {
        public string StatusName { get; set; }
        public string POCode { get; set; }
        public Nullable<int> PoType { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string SONo { get; set; }
        public string OutputNo { get; set; }
        public long Id { get; set; }
        public long SOId { get; set; }
        public long OutputId { get; set; }
        public string CardNo { get; set; }
        public string ZoneType { get; set; }
        public string ZoneNo { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string ZoneTypeName { get; set; }
        public string PoTypeName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IsPrinted { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string SOCompanyNo { get; set; }
        public string SOWmNo { get; set; }
        public Nullable<decimal> PartQty { get; set; }
        public Nullable<decimal> CbmQty { get; set; }
        public Nullable<long> DealerID { get; set; }
        public string ShortName { get; set; }
        public string PartNo { get; set; }
        public string locType { get; set; }
    }
}
