//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPurchasingTarget
    {
        public long Id { get; set; }
        public string DealerCode { get; set; }
        public short Year { get; set; }
        public byte Type { get; set; }
        public int VehicleSalesTarget { get; set; }
        public int BackFrequency { get; set; }
        public int IntoTarget { get; set; }
        public decimal SingleSaleCosts { get; set; }
        public double JanuaryTargetRates { get; set; }
        public double FebuaryTargetRates { get; set; }
        public double MarchTargetRates { get; set; }
        public double AprilTargetRates { get; set; }
        public double MayTargetRates { get; set; }
        public double JuneTargetRates { get; set; }
        public double JulyTargetRates { get; set; }
        public double AugustTargetRates { get; set; }
        public double SeptemberTargetRates { get; set; }
        public double OctoberTargetRates { get; set; }
        public double NovemberTargetRates { get; set; }
        public double DecemberTargetRates { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
