//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPackageTranView
    {
        public long Id { get; set; }
        public string TransNo { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public int TransType { get; set; }
        public string TransTypeName { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public string TransDepartment { get; set; }
        public Nullable<long> TransKeeper { get; set; }
        public string ContactTel { get; set; }
        public string PublishKeeper { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatusName { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Comments { get; set; }
        public bool IsDeleted { get; set; }
        public string Dloc { get; set; }
        public string TrayNo { get; set; }
        public string CreateName { get; set; }
        public string KeeperName { get; set; }
        public string CostCenter { get; set; }
        public string KTEXT { get; set; }
    }
}
