//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPurchaseRebateTotalScoreIntervalView
    {
        public long Id { get; set; }
        public double StartScore { get; set; }
        public double EndScore { get; set; }
        public double Ratio { get; set; }
        public string RatioFormat { get; set; }
        public byte Type { get; set; }
        public string TypeName { get; set; }
    }
}
