//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPurchAsepropertyConfigView
    {
        public Nullable<long> Id { get; set; }
        public string PurchAseproperty { get; set; }
        public string PurchAsepropertyName { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
