//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPartsGroupProfitExtendView
    {
        public string GroupNo { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string OrderTypeName { get; set; }
        public Nullable<int> FreeTimes { get; set; }
        public string PriceGroupCode { get; set; }
        public string PriceGroupName { get; set; }
        public string DealerCode { get; set; }
        public string DealerName { get; set; }
        public string PartNo { get; set; }
        public string PartCname { get; set; }
        public Nullable<decimal> BasicPrice { get; set; }
        public Nullable<decimal> ActualDNP { get; set; }
        public Nullable<decimal> WDNP { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> MSRP { get; set; }
        public Nullable<decimal> ActualMSRP { get; set; }
        public string VersionNum { get; set; }
        public Nullable<System.DateTime> FreeTimeDate { get; set; }
        public Nullable<System.DateTime> ExtendStartDate { get; set; }
        public Nullable<System.DateTime> ExtendEndDate { get; set; }
    }
}
