//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPdaTaskView
    {
        public long Id { get; set; }
        public string BusinessNo { get; set; }
        public string BarcodeData { get; set; }
        public string PartNo { get; set; }
        public decimal ActualNum { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string ZoneNo { get; set; }
        public string Dloc { get; set; }
        public string TargetCompanyNo { get; set; }
        public string TargetWmNo { get; set; }
        public string TargetZoneNo { get; set; }
        public string TargetDloc { get; set; }
        public int TaskType { get; set; }
        public Nullable<long> RepackageId { get; set; }
        public Nullable<System.DateTime> ShelveTime { get; set; }
        public Nullable<long> OnStaff { get; set; }
        public Nullable<long> TransKeeper { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string BufferName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> Status { get; set; }
        public long ModifiedBy { get; set; }
        public string ZoneName { get; set; }
        public string DlocName { get; set; }
        public string TargetZoneName { get; set; }
        public string TargetDlocName { get; set; }
        public Nullable<System.DateTime> RepackageCompleteTime { get; set; }
        public Nullable<long> BookKeeper { get; set; }
        public string AsnNo { get; set; }
        public string NameCn { get; set; }
        public string KeeperName { get; set; }
        public string MoveName { get; set; }
        public string StaffName { get; set; }
        public Nullable<System.DateTime> StartShelveTime { get; set; }
        public string ReceiveNo { get; set; }
        public string TrayNo { get; set; }
        public string StorageTpyeName { get; set; }
    }
}
