//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPickGuideTasksView
    {
        public Nullable<long> Id { get; set; }
        public Nullable<long> CardDetailId { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string ZoneNo { get; set; }
        public string Dloc { get; set; }
        public Nullable<decimal> DemandQuantity { get; set; }
        public Nullable<decimal> TaskQuantity { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string POCode { get; set; }
        public Nullable<int> PoType { get; set; }
        public string SONo { get; set; }
        public long CardID { get; set; }
        public string CardNo { get; set; }
        public string PartNo { get; set; }
        public string PartCname { get; set; }
        public decimal DemandQuantityByPart { get; set; }
        public decimal TotalPackageVol { get; set; }
        public string VIN { get; set; }
        public Nullable<System.DateTime> StartPickTime { get; set; }
    }
}
