//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPartPurchaseForecast
    {
        public long Id { get; set; }
        public string CompanyNo { get; set; }
        public string CompanyName { get; set; }
        public string WmNo { get; set; }
        public string WmName { get; set; }
        public string PartNo { get; set; }
        public string PartCname { get; set; }
        public string LT { get; set; }
        public string MrpType { get; set; }
        public string MakeBuy { get; set; }
        public Nullable<decimal> Stocks { get; set; }
        public Nullable<decimal> OnWayStock { get; set; }
        public Nullable<decimal> OrderCycle { get; set; }
        public Nullable<decimal> ArrivalCycle { get; set; }
        public Nullable<decimal> SafetyStockDay { get; set; }
        public Nullable<decimal> AverageMonthSales { get; set; }
        public Nullable<decimal> Max { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> SafeStock { get; set; }
        public Nullable<decimal> ReplenishmentQuantity { get; set; }
        public Nullable<decimal> Moq { get; set; }
        public Nullable<decimal> Mpq { get; set; }
        public Nullable<decimal> PackageModule { get; set; }
        public Nullable<decimal> AdditionalOrderQuantity { get; set; }
        public Nullable<decimal> SpmSaleFrequency { get; set; }
        public Nullable<decimal> SpmOrderThreshold { get; set; }
        public Nullable<decimal> StandardStock { get; set; }
        public decimal ProposalOrderQuantity { get; set; }
        public Nullable<decimal> DifferenceRatio { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<int> IsNeedStocking { get; set; }
        public Nullable<decimal> Month1 { get; set; }
        public Nullable<decimal> Month2 { get; set; }
        public Nullable<decimal> Month3 { get; set; }
        public Nullable<decimal> Month4 { get; set; }
        public Nullable<decimal> Month5 { get; set; }
        public Nullable<decimal> Month6 { get; set; }
        public Nullable<decimal> Month7 { get; set; }
        public Nullable<decimal> Month8 { get; set; }
        public Nullable<decimal> Month9 { get; set; }
        public Nullable<decimal> Month10 { get; set; }
        public Nullable<decimal> Month11 { get; set; }
        public Nullable<decimal> Month12 { get; set; }
        public string FlowId { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
