//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmPrintAssembleTransHeadView
    {
        public string TransNo { get; set; }
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string PartNo { get; set; }
        public string PartCname { get; set; }
        public string SonCode { get; set; }
        public string SonName { get; set; }
        public Nullable<int> Amount { get; set; }
        public string CreatedByName { get; set; }
        public string Picker { get; set; }
        public string ContactTel { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
    }
}
