//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmRushOrderSetView
    {
        public long Id { get; set; }
        public string GroupNo { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> FreeTimes { get; set; }
        public Nullable<System.DateTime> FreeTimeDate { get; set; }
        public Nullable<System.DateTime> PriceGroupDate { get; set; }
        public Nullable<int> OrderType { get; set; }
        public bool IsDeleted { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string OrderTypeName { get; set; }
        public Nullable<System.DateTime> FreeTimeDateEnd { get; set; }
        public int IsAvailable { get; set; }
    }
}
