//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmStocksStatisticsView
    {
        public string CompanyNo { get; set; }
        public string WmNo { get; set; }
        public string PartNo { get; set; }
        public string ZoneNo { get; set; }
        public decimal SafeStock { get; set; }
        public Nullable<decimal> Stocks { get; set; }
        public Nullable<decimal> AllocateNum { get; set; }
        public Nullable<decimal> FrozenStocks { get; set; }
        public int LocId { get; set; }
    }
}
