//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmShippingOrderExportDetailView
    {
        public long Id { get; set; }
        public string ShippingOrderCode { get; set; }
        public System.DateTime shippingOn { get; set; }
        public string PackingOrderCode { get; set; }
        public string SupplierNo { get; set; }
        public string SupplierName { get; set; }
        public Nullable<System.DateTime> LoadBoxOn { get; set; }
        public string BoxNum { get; set; }
        public string PartNo { get; set; }
        public string NameCn { get; set; }
        public Nullable<decimal> QuantityInBox { get; set; }
        public string SONo { get; set; }
        public Nullable<decimal> DemandQuantity { get; set; }
        public string DealerCode { get; set; }
        public string FullName { get; set; }
        public bool IsDeleted { get; set; }
        public string ExpressNo { get; set; }
        public Nullable<System.DateTime> ReceiveTime { get; set; }
    }
}
