//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpmSODetailView
    {
        public long Id { get; set; }
        public long SOId { get; set; }
        public string SONo { get; set; }
        public string PartNo { get; set; }
        public decimal DemandQuantity { get; set; }
        public decimal ActualQuantity { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string PartCname { get; set; }
        public Nullable<long> POId { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string VIN { get; set; }
        public string POCode { get; set; }
        public Nullable<int> SoStatus { get; set; }
        public Nullable<System.DateTime> SoCreateOn { get; set; }
        public Nullable<int> PoType { get; set; }
        public string DealerCode { get; set; }
    }
}
