//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SsiInvestPaper
    {
        public long Id { get; set; }
        public Nullable<long> QuestionnaireId { get; set; }
        public Nullable<long> RuleId { get; set; }
        public string Department { get; set; }
        public string SurveyCode { get; set; }
        public string Topic { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string AnswererIp { get; set; }
        public Nullable<long> AnswererId { get; set; }
        public string Mobile { get; set; }
        public string Area { get; set; }
        public string OrgId { get; set; }
        public string OrgName { get; set; }
        public string ConsultantId { get; set; }
        public string ConsultantName { get; set; }
        public string AnswererName { get; set; }
        public Nullable<long> RecorderId { get; set; }
        public string RecorderName { get; set; }
        public string UserData { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> BeginAt { get; set; }
        public Nullable<System.DateTime> SubmittedAt { get; set; }
        public Nullable<int> Period { get; set; }
        public string CallbackStatus { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
