//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcAppointmentService
    {
        public long Id { get; set; }
        public string AppointmentCode { get; set; }
        public string OrderType { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<System.DateTime> AppointmentAt { get; set; }
        public Nullable<int> AppointmentSource { get; set; }
        public string SystemOrder { get; set; }
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public Nullable<long> ServiceAdvisorId { get; set; }
        public string ServiceName { get; set; }
        public string AppointmenDescript { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<System.DateTime> MaintainStartAt { get; set; }
        public Nullable<System.DateTime> MaintainEndAt { get; set; }
        public Nullable<long> LaneId { get; set; }
        public string LaneCode { get; set; }
        public string LaneName { get; set; }
        public Nullable<bool> IsPartsNotice { get; set; }
        public string CancelReason { get; set; }
        public Nullable<long> CancelBy { get; set; }
        public Nullable<int> OpSource { get; set; }
        public string OpSourceName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string ChangeReason { get; set; }
        public Nullable<bool> IsTemp { get; set; }
        public string problemDescription { get; set; }
        public string AppointmentRemark { get; set; }
        public Nullable<long> OwendServiceAdvisorId { get; set; }
    }
}
