//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcCscView
    {
        public long Id { get; set; }
        public string CSCCode { get; set; }
        public string SymptomType { get; set; }
        public string FG1 { get; set; }
        public string FG2 { get; set; }
        public string Component { get; set; }
        public string Deviation { get; set; }
        public string Condition1 { get; set; }
        public string Condition2 { get; set; }
        public string Culture { get; set; }
    }
}
