//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcContact
    {
        public long Id { get; set; }
        public Nullable<int> TaskType { get; set; }
        public string SourceCode { get; set; }
        public Nullable<int> TaskSubType { get; set; }
        public string TaskSubTypeLabel { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public string VinCode { get; set; }
        public string Plate { get; set; }
        public string VehicleType { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerTel { get; set; }
        public string OwnerPhone { get; set; }
        public string DealerId { get; set; }
        public string ServerDealerName { get; set; }
        public Nullable<long> ServiceAdvisorId { get; set; }
        public string ServiceName { get; set; }
        public Nullable<int> ContactType { get; set; }
        public Nullable<System.DateTime> PlanAttractAt { get; set; }
        public Nullable<System.DateTime> AttractAt { get; set; }
        public Nullable<int> ContactResultId { get; set; }
        public string ContactResult { get; set; }
        public Nullable<int> ContactRecordCount { get; set; }
        public Nullable<bool> IsHaveRepair { get; set; }
        public Nullable<int> OpSource { get; set; }
        public string OpSourceName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<bool> IsExpiry { get; set; }
        public Nullable<int> ContactResultStatus { get; set; }
        public Nullable<System.DateTime> AttractEndOn { get; set; }
        public Nullable<long> FirstServiceAdvisorId { get; set; }
        public string FirstServiceName { get; set; }
        public Nullable<int> AdvisorLock { get; set; }
        public string ContactSequence { get; set; }
        public string Ex1 { get; set; }
        public Nullable<bool> SendStatus { get; set; }
        public string NoticeRequestId { get; set; }
    }
}
