//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcOrderStoreInfo
    {
        public long Id { get; set; }
        public string SystemOrder { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<bool> IsOwner { get; set; }
        public Nullable<long> SebderId { get; set; }
        public string Sender { get; set; }
        public string SenderPhone { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public string Plate { get; set; }
        public string VinCode { get; set; }
        public string EngineNumber { get; set; }
        public Nullable<System.DateTime> BuyAt { get; set; }
        public string VehicleClass { get; set; }
        public string VehicleName { get; set; }
        public Nullable<long> InsurerId { get; set; }
        public string InsurerName { get; set; }
        public Nullable<System.DateTime> InsurerExpiry { get; set; }
        public Nullable<int> DoorToDoorService { get; set; }
        public string GetAddress { get; set; }
        public string ReturnAddress { get; set; }
        public Nullable<bool> IsWash { get; set; }
        public string TeaBreak { get; set; }
        public string RestMode { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> OldPartsProcess { get; set; }
        public Nullable<int> PayBy { get; set; }
        public string InvoiceHeader { get; set; }
        public Nullable<int> WaitMode { get; set; }
        public Nullable<int> CustomerOrderType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string SenderTel { get; set; }
        public string OwnerTel { get; set; }
        public Nullable<int> AppointmentDiscount { get; set; }
        public string RingCheckPicSize { get; set; }
        public Nullable<System.DateTime> GetOn { get; set; }
        public Nullable<System.DateTime> ReturnOn { get; set; }
        public Nullable<int> ReCallTime { get; set; }
        public Nullable<int> SenderSex { get; set; }
        public Nullable<int> CustomerRelationShip { get; set; }
        public string LookComment { get; set; }
        public Nullable<bool> OwnerSex { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> SendProvince { get; set; }
        public Nullable<long> SendCity { get; set; }
        public Nullable<long> SendDistrict { get; set; }
        public string SendAddress { get; set; }
        public string SendZipCode { get; set; }
        public string SendEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AttractId { get; set; }
        public string AttractType { get; set; }
        public Nullable<bool> IsReserve { get; set; }
        public string SaPlate { get; set; }
        public string SaSender { get; set; }
        public string SaVinCode { get; set; }
        public string ReserveId { get; set; }
        public string VehicleTypeCode { get; set; }
        public Nullable<System.DateTime> ThreeRGuaranteeDay { get; set; }
        public Nullable<bool> Is3R { get; set; }
        public Nullable<int> TakeCarStatus { get; set; }
        public Nullable<int> SendCarStatus { get; set; }
        public string MsgFlag { get; set; }
        public Nullable<System.DateTime> WarrantyPeriod { get; set; }
        public string StartLatitudeLongitude { get; set; }
        public Nullable<decimal> StartKilometers { get; set; }
        public string StartLongTime { get; set; }
        public Nullable<decimal> StartFee { get; set; }
        public string EndLatitudeLongitude { get; set; }
        public Nullable<decimal> EndKilometers { get; set; }
        public string EndLongTime { get; set; }
        public Nullable<decimal> EndFee { get; set; }
        public string OrderNumber { get; set; }
        public string VehicleTag { get; set; }
        public Nullable<bool> IsSpecialOrder { get; set; }
        public Nullable<bool> Dispaly { get; set; }
    }
}
