//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcProxyOperationLaneView
    {
        public string systemOrder { get; set; }
        public long proxyId { get; set; }
        public Nullable<System.DateTime> expectFinishAt { get; set; }
        public Nullable<System.DateTime> expectStartAt { get; set; }
        public Nullable<System.DateTime> finishAt { get; set; }
        public Nullable<System.DateTime> startAt { get; set; }
        public Nullable<int> status { get; set; }
        public string orderType { get; set; }
        public string serviceAdvisorName { get; set; }
        public string plate { get; set; }
        public string vehicleName { get; set; }
        public string serviceType { get; set; }
        public string serviceContent { get; set; }
        public string maintainItemCode { get; set; }
        public string maintainItemName { get; set; }
        public Nullable<long> operId { get; set; }
        public Nullable<int> pauseType { get; set; }
        public Nullable<bool> isWash { get; set; }
        public string laneCode { get; set; }
        public Nullable<long> laneId { get; set; }
        public string laneName { get; set; }
        public string groupName { get; set; }
        public Nullable<long> techId { get; set; }
        public string techName { get; set; }
        public Nullable<long> opLaneId { get; set; }
    }
}
