//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcStatementPayDetail
    {
        public long Id { get; set; }
        public string StatementNo { get; set; }
        public string SystemOrder { get; set; }
        public Nullable<int> StatemenrManType { get; set; }
        public Nullable<long> ManId { get; set; }
        public string ManName { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string PayType { get; set; }
        public string InvoiceType { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> AccountType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string ClaimNum { get; set; }
        public string Handler { get; set; }
        public string CashBatch { get; set; }
        public Nullable<decimal> RevertCash { get; set; }
        public Nullable<System.DateTime> RevertTime { get; set; }
        public Nullable<System.DateTime> RevertAuditTime { get; set; }
        public Nullable<int> RevertAuditStatus { get; set; }
        public Nullable<long> RevertAuditorId { get; set; }
        public Nullable<long> RevertOperorId { get; set; }
        public string RevertAuditorName { get; set; }
        public string RevertOperorName { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public string CashierRemarks { get; set; }
    }
}
