//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcServiceMutualCheckModel_zhb180125
    {
        public long Id { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public string ItemValueOne { get; set; }
        public string ItemUnitOne { get; set; }
        public string ItemValueTwo { get; set; }
        public string ItemUnitTwo { get; set; }
        public string ItemValueThree { get; set; }
        public string ItemUnitThree { get; set; }
        public string ItemValueFour { get; set; }
        public string ItemUnitFour { get; set; }
        public Nullable<int> TypeSeq { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
