//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcSendLog
    {
        public string SendName { get; set; }
        public string Plate { get; set; }
        public string Vin { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<int> OwnerRelations { get; set; }
        public Nullable<long> OwnerAccountId { get; set; }
        public string DealerCode { get; set; }
        public long SendCount { get; set; }
        public Nullable<long> OwnerContactId { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<long> Province { get; set; }
        public Nullable<long> City { get; set; }
        public Nullable<long> District { get; set; }
        public string ZipCode { get; set; }
        public string TelPhone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public long Id { get; set; }
    }
}
