//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcVehcileCustomerView
    {
        public long VehicleId { get; set; }
        public string LicenseNo { get; set; }
        public string VIN { get; set; }
        public Nullable<long> Pno18 { get; set; }
        public string Pno18Code { get; set; }
        public string EngineNumber { get; set; }
        public string EngineName { get; set; }
        public string GearNumber { get; set; }
        public string GearboxName { get; set; }
        public Nullable<int> VehicleAttribute { get; set; }
        public Nullable<System.DateTime> Instock { get; set; }
        public Nullable<bool> Isopra { get; set; }
        public Nullable<System.DateTime> Lastkeepdate { get; set; }
        public Nullable<decimal> Lastkeepmile { get; set; }
        public Nullable<System.DateTime> Lastrepairdate { get; set; }
        public Nullable<decimal> Lastrepairmile { get; set; }
        public Nullable<decimal> Latestmile { get; set; }
        public Nullable<System.DateTime> Latestkeepdate { get; set; }
        public Nullable<System.DateTime> Manufacturingdate { get; set; }
        public string Photourl { get; set; }
        public Nullable<int> SaleStatus { get; set; }
        public Nullable<int> PDIStatus { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public string VehicleTag { get; set; }
        public string VehicleClass { get; set; }
        public string VehicleTypeCode { get; set; }
        public string VehicleTypeName { get; set; }
        public string ColorName { get; set; }
        public Nullable<bool> Is3r { get; set; }
        public Nullable<long> InsuranceId { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceName { get; set; }
        public Nullable<System.DateTime> Insurancestartdate { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string WarrantyDate { get; set; }
        public Nullable<long> Salesdealerid { get; set; }
        public string SaleDealerName { get; set; }
        public string SaleDealerShortName { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<long> DealerID { get; set; }
        public string DealerCode { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string fullName { get; set; }
        public string NickName { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerMobilePhone { get; set; }
        public string GovernmentId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> GenderCode { get; set; }
        public string MobilePhone { get; set; }
        public string Telephone { get; set; }
        public string EmailAddress { get; set; }
        public string ZipCode { get; set; }
        public string CustomerCompany { get; set; }
        public string Address { get; set; }
        public Nullable<long> Province { get; set; }
        public string ProvinceName { get; set; }
        public Nullable<long> City { get; set; }
        public string CityName { get; set; }
        public Nullable<long> District { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> CustomerCatalog { get; set; }
        public string DealerName { get; set; }
        public string DealerShortName { get; set; }
        public Nullable<int> CustomerTag { get; set; }
        public string Description { get; set; }
        public Nullable<int> DataFrom { get; set; }
        public string AreaCode1 { get; set; }
        public string Telephone1 { get; set; }
        public string Company { get; set; }
        public string Business2 { get; set; }
        public string Suffix { get; set; }
        public Nullable<int> ContactStatus { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string UserAccount { get; set; }
        public Nullable<long> UniqueLeadId { get; set; }
        public Nullable<long> UniqueLead { get; set; }
        public string Education { get; set; }
        public string Profession { get; set; }
        public string Religion { get; set; }
        public string Marriage { get; set; }
        public string race { get; set; }
        public string Customerlabel { get; set; }
    }
}
