//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SvcVehicleDelivery
    {
        public long Id { get; set; }
        public Nullable<int> PdiStatus { get; set; }
        public Nullable<int> DeliveryItenStatus { get; set; }
        public string SaleOrderNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string InvoicePath { get; set; }
        public string IdCardPath { get; set; }
        public Nullable<long> ServiceAdvisorId { get; set; }
        public string ServiceAdvisorName { get; set; }
        public string DealerId { get; set; }
        public string ServerDealerName { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public string Plate { get; set; }
        public string VinCode { get; set; }
        public string VehicleType { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public Nullable<System.DateTime> DeliveryPlanOn { get; set; }
        public Nullable<System.DateTime> DeliveryOn { get; set; }
        public Nullable<long> ExecuteById { get; set; }
        public string ExecuteBy { get; set; }
        public Nullable<bool> IsHaveBoutique { get; set; }
        public Nullable<bool> IsUpload { get; set; }
        public Nullable<int> ReturnVisitAt { get; set; }
        public Nullable<int> ReturnVisitBy { get; set; }
        public Nullable<int> OpSource { get; set; }
        public string OpSourceName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string SystemOrder { get; set; }
        public Nullable<bool> IsExpiry { get; set; }
        public string OwnerTel { get; set; }
        public Nullable<long> FirstServiceAdvisorId { get; set; }
        public string FirstServiceAdvisorName { get; set; }
        public Nullable<int> AdvisorLock { get; set; }
        public Nullable<bool> SaleDelivery { get; set; }
    }
}
