//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsAdvisoryOrderView
    {
        public string advTheme { get; set; }
        public long id { get; set; }
        public string orderId { get; set; }
        public Nullable<int> importantLevel { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> threelineStatus { get; set; }
        public Nullable<int> orderStatus { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> orderType { get; set; }
        public string codeVIN { get; set; }
        public string plateNumber { get; set; }
        public string codeCSC { get; set; }
        public Nullable<System.DateTime> faultDate { get; set; }
        public string functionalGroup { get; set; }
        public string partsCode { get; set; }
        public string brand { get; set; }
        public int ftType { get; set; }
        public string carSeries { get; set; }
        public string carModel { get; set; }
        public string distributor { get; set; }
    }
}
