//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsApprovalRecordInfoView
    {
        public long id1 { get; set; }
        public Nullable<long> foreignid { get; set; }
        public Nullable<long> approvedBy { get; set; }
        public Nullable<System.DateTime> approvedOn { get; set; }
        public string approvalView { get; set; }
        public string approvalType { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<long> id { get; set; }
        public Nullable<long> userCode { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public Nullable<int> integral { get; set; }
        public string position { get; set; }
        public string twoposition { get; set; }
        public string threeposition { get; set; }
        public string department { get; set; }
        public string classification { get; set; }
        public string continent { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string dealerCode { get; set; }
        public string shortName { get; set; }
        public string fullName { get; set; }
        public string certificationLevels { get; set; }
        public string skilledField { get; set; }
        public Nullable<int> workingAge { get; set; }
        public Nullable<int> workingConditions { get; set; }
        public Nullable<double> responderResponsivity { get; set; }
        public string bbsActive { get; set; }
        public string goodAtBrand { get; set; }
        public string onLine { get; set; }
        public string attr { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<int> @checked { get; set; }
        public string IsAdmin { get; set; }
        public string roleids { get; set; }
        public string postids { get; set; }
        public string mobile { get; set; }
        public string rolecodes { get; set; }
    }
}
