//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsCarMaintenanceCaseView
    {
        public long id { get; set; }
        public string theme { get; set; }
        public string applicationNo { get; set; }
        public string userType { get; set; }
        public string marketCode { get; set; }
        public string brand { get; set; }
        public string carSeries { get; set; }
        public string carModel { get; set; }
        public string version { get; set; }
        public string steering { get; set; }
        public string drivenType { get; set; }
        public string functionalGroup { get; set; }
        public string codeDTC { get; set; }
        public string reasonCode { get; set; }
        public string engineNo { get; set; }
        public string engineDescription { get; set; }
        public string faultType { get; set; }
        public string gearboxNo { get; set; }
        public string gearboxDescription { get; set; }
        public string codeCSC { get; set; }
        public Nullable<System.DateTime> repairDate { get; set; }
        public Nullable<int> partsCode { get; set; }
        public string publisher { get; set; }
        public string createdBy { get; set; }
        public string createdByName { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public Nullable<int> readingQuantity { get; set; }
        public Nullable<int> collection { get; set; }
    }
}
