//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsCommunicateInfo
    {
        public long Id { get; set; }
        public Nullable<long> ReportId { get; set; }
        public Nullable<System.DateTime> AlarmTime { get; set; }
        public Nullable<System.DateTime> ResponseTime { get; set; }
        public Nullable<System.DateTime> DealWithTime { get; set; }
        public string PersonLiable { get; set; }
        public string Telephone { get; set; }
        public string Describe { get; set; }
        public string Sample { get; set; }
        public string AccidentResponsibility { get; set; }
        public Nullable<bool> HasInsurance { get; set; }
        public Nullable<bool> HasWatch { get; set; }
        public string InsuranceCompanyName { get; set; }
        public Nullable<System.DateTime> WatchTime { get; set; }
        public string InsuranceAttitude { get; set; }
        public string UserAttitude { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    }
}
