//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsFlowDocView
    {
        public long id { get; set; }
        public string FirstId { get; set; }
        public string ChangeId { get; set; }
        public string ChangeType { get; set; }
        public string Instruction { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string name { get; set; }
        public string job { get; set; }
        public string position { get; set; }
    }
}
