//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsHotlineFAQ
    {
        public long Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequnece { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string Numbers { get; set; }
        public string AdvTheme { get; set; }
        public string MatterType { get; set; }
        public string FunctionRange { get; set; }
        public string ChassisNo { get; set; }
        public string ManufacturingBase { get; set; }
        public string InfoCSC { get; set; }
        public string FaultType { get; set; }
        public string Vin { get; set; }
        public string PlatForm { get; set; }
        public string CarSeries { get; set; }
        public string CarModel { get; set; }
        public string FaulDescribe { get; set; }
        public string Solution { get; set; }
    }
}
