//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsPendingMsg
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public string McId { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public string CallbackUrl { get; set; }
        public Nullable<System.DateTime> InvalidateAt { get; set; }
        public Nullable<System.DateTime> StartupAt { get; set; }
        public string App { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string AppTag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Commons { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
