//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsReverseWarrantyCarView
    {
        public long id { get; set; }
        public long dealerid { get; set; }
        public string warrantyno { get; set; }
        public string vin { get; set; }
        public string infoCSC { get; set; }
        public string describeCSC { get; set; }
        public string codeVIN { get; set; }
        public string platForm { get; set; }
        public string BrandName { get; set; }
        public string carSeries { get; set; }
        public string carModel { get; set; }
        public string plateNumber { get; set; }
        public string modelYear { get; set; }
        public string bazaarCode { get; set; }
        public Nullable<System.DateTime> salesDate { get; set; }
        public string Version { get; set; }
        public Nullable<int> vehicleAttributes { get; set; }
        public string steering { get; set; }
        public string engineSerialNo { get; set; }
        public string engineDescription { get; set; }
        public Nullable<long> fyon { get; set; }
        public string chassismodel { get; set; }
        public string structureWeek { get; set; }
        public string type { get; set; }
        public string gearboxSerialNo { get; set; }
        public string gearboxDescription { get; set; }
        public Nullable<long> assemblyPlant { get; set; }
        public Nullable<System.DateTime> productionDate { get; set; }
        public Nullable<System.DateTime> arrivalTime { get; set; }
        public Nullable<System.DateTime> faultDate { get; set; }
        public Nullable<int> mileage { get; set; }
        public string Unit { get; set; }
        public string maintenanceNo { get; set; }
        public string bodynumber { get; set; }
        public string enginePartNo { get; set; }
        public string gearboxPartNo { get; set; }
    }
}
