//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSResponseStatisticsView
    {
        public string DealerId { get; set; }
        public string DealerName { get; set; }
        public string CityName { get; set; }
        public string ProvinceName { get; set; }
        public string CountryName { get; set; }
        public string SmallRegionName { get; set; }
        public string BigRegionName { get; set; }
        public long Id { get; set; }
        public string OrderType { get; set; }
        public string PlatForm { get; set; }
        public string CarModel { get; set; }
        public string ModelYear { get; set; }
        public string CodeVIN { get; set; }
        public string EnginePartNo { get; set; }
        public string GearboxPartNo { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public string ApprovalTypeName { get; set; }
        public Nullable<int> ClosedLoopHour { get; set; }
        public Nullable<int> Responses { get; set; }
        public Nullable<decimal> ResponseTime { get; set; }
        public Nullable<int> RepeatApprovalCount { get; set; }
    }
}
