//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsRepairCollectListView
    {
        public long Id { get; set; }
        public string DealerId { get; set; }
        public string ThreeLine { get; set; }
        public Nullable<long> customerServiceDirector { get; set; }
        public Nullable<long> amqDirector { get; set; }
        public Nullable<long> threeRDDirector { get; set; }
        public Nullable<long> diagnosticInstrumentDirector { get; set; }
        public string OrderId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string AdvTheme { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DealerStatus { get; set; }
        public string CustomerServiceSecondStatus { get; set; }
        public string CustomerServiceStatus { get; set; }
        public Nullable<int> Reading { get; set; }
        public Nullable<int> Collection { get; set; }
        public string Brand { get; set; }
        public string FaultType { get; set; }
        public string DrivenType { get; set; }
        public string FunctionalGroup { get; set; }
        public string comments { get; set; }
        public string Name { get; set; }
        public string infoCSC { get; set; }
        public string ReasonCode { get; set; }
        public string allStatus { get; set; }
        public string Continent { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Province { get; set; }
        public string DealerCode { get; set; }
        public string ShortName { get; set; }
        public string Country { get; set; }
        public string CodeDTC { get; set; }
        public string CarSeries { get; set; }
        public string CarModel { get; set; }
        public string MarketCode { get; set; }
        public string EngineNo { get; set; }
        public string GearboxNo { get; set; }
        public string Steering { get; set; }
        public string EngineDescription { get; set; }
        public string GearboxDescription { get; set; }
        public string Version { get; set; }
        public string ModelYear { get; set; }
        public string FaultDescription { get; set; }
        public string Diagnosis { get; set; }
        public string Measure { get; set; }
        public string Question { get; set; }
        public string FunctionGroup { get; set; }
        public string CodePSS { get; set; }
        public Nullable<long> DistributorId { get; set; }
        public Nullable<int> readType { get; set; }
    }
}
