//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsReleaseObject
    {
        public long Id { get; set; }
        public Nullable<long> ServiceNotificationId { get; set; }
        public string Chau { get; set; }
        public string Countries { get; set; }
        public string Regional { get; set; }
        public string Dealers { get; set; }
        public string DealersCode { get; set; }
        public Nullable<System.DateTime> FirstTime { get; set; }
        public Nullable<int> ReadNum { get; set; }
        public Nullable<int> DownloadNum { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequnece { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreateBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string Province { get; set; }
    }
}
