//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsSelectServiceReportView
    {
        public long id { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public string DealerStatus { get; set; }
        public string OrderId { get; set; }
        public string AdvTheme { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string maintenanceStatus { get; set; }
        public string NotificationTwoType { get; set; }
        public string La { get; set; }
        public string Range { get; set; }
        public string CarModel { get; set; }
        public string InfoCSC { get; set; }
        public string FunctionalGroup { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Reading { get; set; }
        public Nullable<int> Collection { get; set; }
        public string ThreeLine { get; set; }
        public string CustomerServiceStatus { get; set; }
        public string CustomerServiceSecondStatus { get; set; }
        public string dealerCodes { get; set; }
        public Nullable<System.DateTime> publishTime { get; set; }
    }
}
