//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsServiceDescribe
    {
        public long Id { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequnece { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string Language { get; set; }
        public string Range { get; set; }
        public string FunctionGroup { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> PartStatus { get; set; }
        public string Describe { get; set; }
        public string ProductImprovement { get; set; }
        public string TechnicalReport { get; set; }
        public string RepairInfo { get; set; }
        public string Matter { get; set; }
        public string PlotDescribe { get; set; }
        public string Countermeasure { get; set; }
        public string Policy { get; set; }
        public string Measures { get; set; }
        public string Guidance { get; set; }
        public string OutsourceInfo { get; set; }
        public string ResponsiblePerson { get; set; }
        public string UpdateDescription { get; set; }
        public string GroupTwo { get; set; }
        public string GroupThree { get; set; }
        public string GroupFour { get; set; }
        public string GroupFive { get; set; }
    }
}
