//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsServiceNotificationView
    {
        public string theme { get; set; }
        public long orderId { get; set; }
        public string reportNo { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> carSeries { get; set; }
        public string carModel { get; set; }
        public string type { get; set; }
        public string language { get; set; }
        public Nullable<System.DateTime> repairDate { get; set; }
        public Nullable<System.DateTime> notificationDate { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public string functionalGroup { get; set; }
        public string codeCSC { get; set; }
        public string range { get; set; }
        public Nullable<int> readingQuantity { get; set; }
        public Nullable<int> downloads { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
    }
}
