//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsSeniorTecConsultView
    {
        public string CustomerServiceStatus { get; set; }
        public string bcStatus { get; set; }
        public long Id { get; set; }
        public string CustomerServiceSecondStatus { get; set; }
        public string DealerId { get; set; }
        public string ThreeLine { get; set; }
        public string thirdStatus { get; set; }
        public string MaintenanceStatus { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string OrderId { get; set; }
        public string role { get; set; }
        public string AdvTheme { get; set; }
        public string CodeVIN { get; set; }
        public string PlateNumber { get; set; }
        public string StructureWeek { get; set; }
        public string Type { get; set; }
        public string Version { get; set; }
        public string AssemblyPlant { get; set; }
        public string EngineSerialNo { get; set; }
        public string EngineDescription { get; set; }
        public string VehicleAttributes { get; set; }
        public string ReasonCode { get; set; }
        public string GearboxSerialNo { get; set; }
        public string GearboxDescription { get; set; }
        public string WorkTimeCode { get; set; }
        public string Steering { get; set; }
        public Nullable<long> customerServiceDirector { get; set; }
        public Nullable<long> amqDirector { get; set; }
        public Nullable<long> threeRDDirector { get; set; }
        public Nullable<long> diagnosticInstrumentDirector { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string InfoCSC { get; set; }
        public string goiqr { get; set; }
        public Nullable<int> orderstatus { get; set; }
        public string Content { get; set; }
        public Nullable<int> TracksType { get; set; }
        public string CarSeries { get; set; }
        public string CarModel { get; set; }
        public string Brand { get; set; }
        public string ModelYear { get; set; }
        public string BazaarCode { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public string PartsName { get; set; }
        public string CodePSS { get; set; }
        public string SuspiciousPartsNo { get; set; }
        public Nullable<System.DateTime> FaultDate { get; set; }
        public Nullable<int> FaultType { get; set; }
        public string FunctionGroup { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public string changeName { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DealerStatus { get; set; }
        public string continent { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string dealerCode { get; set; }
        public string shortName { get; set; }
        public Nullable<int> labeltype { get; set; }
        public string label { get; set; }
        public string CodeDTC { get; set; }
        public string FaultDescription { get; set; }
        public string Diagnosis { get; set; }
        public string Measure { get; set; }
        public string Question { get; set; }
        public Nullable<bool> IsRepaired { get; set; }
        public string RepairInstructions { get; set; }
        public string RepairResult { get; set; }
        public string contentSearch { get; set; }
        public string threeStatus { get; set; }
        public Nullable<System.DateTime> firstResponseTime { get; set; }
    }
}
