//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsSeniorGldsQeView
    {
        public long Id { get; set; }
        public string dealerId { get; set; }
        public string dealerName { get; set; }
        public string dealerStatus { get; set; }
        public string customerServiceStatus { get; set; }
        public string customerServiceSecondStatus { get; set; }
        public string OrderId { get; set; }
        public string AdvTheme { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> Classification { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ThreelineStatus { get; set; }
        public string name { get; set; }
        public string ThreeLine { get; set; }
        public string continent { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string dealerCode { get; set; }
        public string engineer { get; set; }
    }
}
