//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsSpecialReportView
    {
        public long Id { get; set; }
        public string OrderId { get; set; }
        public string AdvTheme { get; set; }
        public Nullable<int> ImportantLevel { get; set; }
        public string Asker { get; set; }
        public string Position { get; set; }
        public string Telephone { get; set; }
        public Nullable<long> CarInfoId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Feedback { get; set; }
        public string Worker { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string OtherOrderId { get; set; }
        public string Content { get; set; }
        public Nullable<int> AuthorizedBy { get; set; }
        public Nullable<decimal> PartsMoney { get; set; }
        public Nullable<decimal> WorkTimeMoney { get; set; }
        public Nullable<decimal> OtherMoney { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> QualityReportType { get; set; }
        public Nullable<int> ReportType { get; set; }
        public Nullable<int> ReportForm { get; set; }
        public Nullable<int> ThreelineStatus { get; set; }
        public string CommentOther { get; set; }
        public string DealerStatus { get; set; }
        public string ThreeLine { get; set; }
        public string CustomerServiceStatus { get; set; }
        public string MaintenanceStatus { get; set; }
        public string PartsCurrency { get; set; }
        public string WorkTimCurrency { get; set; }
        public string OtherCurrency { get; set; }
        public string CurrentApprovalLevel { get; set; }
        public string MaxApprovalLevel { get; set; }
        public string DealerId { get; set; }
        public string OnsiteSupportApplication { get; set; }
        public string OtherOrderIds { get; set; }
        public string CommentOthers { get; set; }
        public string CustomerServiceSecondStatus { get; set; }
        public string QualityReportId { get; set; }
        public Nullable<int> Classification { get; set; }
        public string OneOther { get; set; }
        public string TwoOther { get; set; }
        public Nullable<int> TracksType { get; set; }
        public Nullable<int> ReturnParts { get; set; }
        public Nullable<System.DateTime> OtherTime { get; set; }
        public Nullable<bool> ConsultStatus { get; set; }
        public Nullable<int> Reading { get; set; }
        public Nullable<int> Collection { get; set; }
        public string Role { get; set; }
        public string DealerName { get; set; }
        public string Email { get; set; }
        public string Edition { get; set; }
        public string NotificationOneType { get; set; }
        public string NotificationTwoType { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string BaseNumber { get; set; }
        public string WarrantyClaim { get; set; }
        public Nullable<long> LabelId { get; set; }
        public string Path { get; set; }
        public string name { get; set; }
        public string PlateNumber { get; set; }
        public string CarModel { get; set; }
        public string Brand { get; set; }
        public string CarSeries { get; set; }
        public string region { get; set; }
        public string province { get; set; }
        public string CodeDTC { get; set; }
        public string CodeECU { get; set; }
        public string InfoCSC { get; set; }
        public string FunctionalGroup { get; set; }
        public string TecConsultOrder { get; set; }
        public string TecConsultComment { get; set; }
    }
}
