//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicalFornumFriendView
    {
        public long id { get; set; }
        public Nullable<long> lid { get; set; }
        public Nullable<long> rid { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> status { get; set; }
        public string nickName { get; set; }
        public Nullable<long> userCode { get; set; }
        public string image { get; set; }
        public string name { get; set; }
        public string certificationLevels { get; set; }
        public string shortName { get; set; }
        public string department { get; set; }
        public string isAdmin { get; set; }
    }
}
