//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicalFornumHomeElitePostView
    {
        public long id { get; set; }
        public string type { get; set; }
        public string theme { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> replyNum { get; set; }
        public int viewNum { get; set; }
        public int downNum { get; set; }
    }
}
