//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicalForumOpertionHistoryView
    {
        public long id { get; set; }
        public string postName { get; set; }
        public Nullable<int> viewNum { get; set; }
        public string type { get; set; }
        public string createName { get; set; }
        public Nullable<System.DateTime> stopTime { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string labels { get; set; }
        public Nullable<long> postId { get; set; }
    }
}
