//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicalFornumNewsListView
    {
        public long id { get; set; }
        public string type { get; set; }
        public string theme { get; set; }
        public Nullable<long> entityId { get; set; }
        public Nullable<System.DateTime> entityTime { get; set; }
        public string comments { get; set; }
        public long receiver { get; set; }
        public string content { get; set; }
        public string OldType { get; set; }
        public string newType { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string remark { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<long> informantsId { get; set; }
        public Nullable<long> replyId { get; set; }
        public Nullable<int> num { get; set; }
    }
}
