//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicalForumGoodsCateforyView
    {
        public long id { get; set; }
        public string type { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> sequnece { get; set; }
        public string comments { get; set; }
        public Nullable<int> num { get; set; }
    }
}
