//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTechnicianView
    {
        public long id { get; set; }
        public long userCode { get; set; }
        public string shortName { get; set; }
        public string name { get; set; }
        public string goodAtBrandcode { get; set; }
        public string goodAtBrand { get; set; }
        public string skilledFieldcode { get; set; }
        public string skilledField { get; set; }
        public string certificationLevels { get; set; }
        public string certificationcode { get; set; }
        public Nullable<int> workingAge { get; set; }
        public string onLine { get; set; }
        public string onLinecode { get; set; }
        public Nullable<int> accountstatus { get; set; }
        public string accountstatuscode { get; set; }
        public Nullable<int> workingConditionscode { get; set; }
        public Nullable<int> workingConditions { get; set; }
        public string continent { get; set; }
        public string country { get; set; }
        public string region { get; set; }
        public string dealerCode { get; set; }
        public string position { get; set; }
        public string postids { get; set; }
        public Nullable<System.DateTime> inductiontime { get; set; }
        public Nullable<int> status { get; set; }
        public string education { get; set; }
        public string major { get; set; }
        public Nullable<double> responderResponsivity { get; set; }
        public string bbsActive { get; set; }
    }
}
