//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsVehicleArrivalView
    {
        public string codevin { get; set; }
        public string carmodel { get; set; }
        public string engineserialno { get; set; }
        public string enginedescription { get; set; }
        public string version { get; set; }
        public Nullable<int> cardoor { get; set; }
        public string gearboxserialno { get; set; }
        public string gearboxdescription { get; set; }
        public string steering { get; set; }
        public string modelYear { get; set; }
        public Nullable<long> originplace { get; set; }
        public string chassismodel { get; set; }
        public string structureWeek { get; set; }
        public Nullable<System.DateTime> arrivalTime { get; set; }
        public string plateNumber { get; set; }
        public string csc { get; set; }
        public string dearlerid { get; set; }
    }
}
