//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehCarTransfer
    {
        public long Id { get; set; }
        public string VIN { get; set; }
        public Nullable<byte> ReferOrderType { get; set; }
        public string ReferOrderCode { get; set; }
        public long OutStoreLocationId { get; set; }
        public long InStoreLocationId { get; set; }
        public Nullable<byte> TransferType { get; set; }
        public Nullable<System.DateTime> MoveOutTime { get; set; }
        public Nullable<System.DateTime> MoveInTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<int> Reason { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    
        public virtual VehStoreLocation VehStoreLocation { get; set; }
        public virtual VehStoreLocation VehStoreLocation1 { get; set; }
    }
}
