//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehCarInventoryView
    {
        public long Id { get; set; }
        public string InventoryCode { get; set; }
        public int Status { get; set; }
        public bool IsCarCheck { get; set; }
        public bool IsCertificationCheck { get; set; }
        public System.DateTime CheckDate { get; set; }
        public bool IsDeleted { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public Nullable<long> CheckUserId { get; set; }
        public Nullable<long> CertificationCheckUserId { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public string WarehouseName { get; set; }
        public string CreatedUserName { get; set; }
        public string CheckUserName { get; set; }
        public string CheckUserNo { get; set; }
        public string CertificationCheckUserName { get; set; }
        public string CertificationCheckUserNo { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> CheckReason { get; set; }
        public string Comments { get; set; }
    }
}
