//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehCarrierBillDeliveryOrderView
    {
        public long Id { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DealerId { get; set; }
        public string Code { get; set; }
        public string ToWarehouseId { get; set; }
        public string DeliveryOrderCode { get; set; }
        public Nullable<byte> DeliveryOrderReferOrderType { get; set; }
        public string ReferOrderCode { get; set; }
        public Nullable<long> CurrentWarehouseId { get; set; }
        public string ShipmentLineCode { get; set; }
        public Nullable<long> DeliveryOrderId { get; set; }
        public string DealerCode { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
    }
}
