//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehDeliveryOrderCarView
    {
        public long Id { get; set; }
        public long DeliveryOrderId { get; set; }
        public string VIN { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string VehicleTypeName { get; set; }
        public string StyleName { get; set; }
        public string EngineName { get; set; }
        public string VehicleYear { get; set; }
        public string VehicleDisplacement { get; set; }
        public string OptionsName { get; set; }
        public string ConfigurationName { get; set; }
        public string ColorName { get; set; }
        public string VehicleTypeCode { get; set; }
        public string VehicleDisplacementCode { get; set; }
        public string SONO { get; set; }
        public Nullable<int> CapitalType { get; set; }
        public Nullable<int> SoreviewStatus { get; set; }
        public string DeliveryOrderCode { get; set; }
        public Nullable<byte> DeliveryOrderReferOrderType { get; set; }
        public string DeliveryOrderReferOrderCode { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> DeliveryOrderStatus { get; set; }
        public string CapitalTypeName { get; set; }
        public string ProfileWarehouseStatusName { get; set; }
        public Nullable<int> ProfileWarehouseStatus { get; set; }
        public Nullable<long> WarehouseId { get; set; }
        public string PNO18 { get; set; }
        public string WarehouseCode { get; set; }
    }
}
