//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDelivery
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public Nullable<long> RetailOrder { get; set; }
        public string FinancialSolution { get; set; }
        public Nullable<bool> IsfinancialSolution { get; set; }
        public Nullable<int> FinancialApproval { get; set; }
        public Nullable<int> SalesApproval { get; set; }
        public Nullable<int> PdiApproval { get; set; }
        public Nullable<int> OutApproval { get; set; }
        public Nullable<int> InvoiceApproval { get; set; }
        public Nullable<long> PdiCheckList { get; set; }
        public Nullable<long> Vehicle { get; set; }
        public string Voucherno { get; set; }
        public Nullable<int> DeliveryStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> Dealer { get; set; }
        public Nullable<long> Warehouse { get; set; }
        public Nullable<long> Customer { get; set; }
        public string CarLinkNo { get; set; }
        public Nullable<System.DateTime> LinkDate { get; set; }
        public Nullable<bool> IsKey { get; set; }
        public Nullable<bool> IsJack { get; set; }
        public Nullable<bool> LunTaiTaoTong { get; set; }
        public Nullable<bool> GuZhangJShiPai { get; set; }
        public Nullable<bool> BeiTai { get; set; }
        public Nullable<bool> CheLiangWaiGuanQingJie { get; set; }
        public Nullable<bool> CheNeiGanJing { get; set; }
        public Nullable<bool> ZuoYiTiaoZheng { get; set; }
        public Nullable<bool> FangXiangPanTiaoZheng { get; set; }
        public Nullable<bool> HouShiJingTiaoZheng { get; set; }
        public Nullable<bool> DianDongMenChuang { get; set; }
        public Nullable<bool> ErTongAnQuanSuo { get; set; }
        public Nullable<bool> KongTiaoChuWu { get; set; }
        public Nullable<bool> DengGuangYiBiao { get; set; }
        public Nullable<bool> YinXiang { get; set; }
        public Nullable<bool> LunTaiQiYaDaXiao { get; set; }
        public Nullable<bool> TeYouPeiZhi { get; set; }
        public Nullable<bool> DaoCheLeiDa { get; set; }
        public Nullable<bool> TianChuang { get; set; }
        public Nullable<bool> ZhuJiaShiQiNang { get; set; }
        public Nullable<bool> FuJiaShiQiNang { get; set; }
        public Nullable<bool> Abs { get; set; }
        public Nullable<bool> FangDaoZhuangZhi { get; set; }
        public string QiTaClzt { get; set; }
        public Nullable<bool> GouCheFaPiao { get; set; }
        public Nullable<bool> BaoYangShouCe { get; set; }
        public Nullable<bool> GouXiaoHeTong { get; set; }
        public Nullable<bool> QiCheXingShiZheng { get; set; }
        public Nullable<bool> JiCheDengJiZheng { get; set; }
        public Nullable<bool> BaoXianDanJu { get; set; }
        public Nullable<bool> GouZhiShuiJiaoNa { get; set; }
        public Nullable<bool> ShangPaiFeiYongFaPiao { get; set; }
        public string QiTaShangPai { get; set; }
        public Nullable<bool> ShiYongShouCeShuoMing { get; set; }
        public Nullable<bool> FuWuBaoXiuNeiRong { get; set; }
        public Nullable<bool> MianFeiBaoYangGaoZhi { get; set; }
        public Nullable<bool> FuWuZhanWeiZhi { get; set; }
        public Nullable<bool> YingYeShiJian { get; set; }
        public Nullable<bool> JieShaoFuWuRenYuan { get; set; }
        public Nullable<bool> MianFeiFuWuReXian { get; set; }
        public Nullable<bool> JingJiQingKuang { get; set; }
        public Nullable<bool> ShouBaoShiJianJieShao { get; set; }
        public Nullable<bool> YongQiZhuYiShiXiang { get; set; }
        public Nullable<bool> YuYueHuiChangXiaoXi { get; set; }
        public Nullable<bool> YouShuiQiTiTianJia { get; set; }
        public string QiTaWenXingFuWu { get; set; }
        public Nullable<bool> HeGeZheng { get; set; }
        public Nullable<bool> ShiYongShuoMingShu { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<long> PdiDealer { get; set; }
        public Nullable<int> VehicleDeliveryFrom { get; set; }
        public Nullable<bool> FunctionCheck { get; set; }
        public Nullable<bool> AttachmentCheck { get; set; }
        public Nullable<System.DateTime> AppointmentTime { get; set; }
        public string AppointmentDesc { get; set; }
    }
}
