//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehScrewJointResult
    {
        public long Id { get; set; }
        public Nullable<long> BoltId { get; set; }
        public string Attempt { get; set; }
        public string Time { get; set; }
        public string BoltStatus { get; set; }
        public string StatusText { get; set; }
        public string TorqueT1 { get; set; }
        public string TorqueT2 { get; set; }
        public string DownRunningAngleA2 { get; set; }
        public string MinDownRunningAngleA2LL { get; set; }
        public string MaxDownRunningAngleA2HL { get; set; }
        public string TorqueT3 { get; set; }
        public string FinalTorqueT4 { get; set; }
        public string TargetTorqueT4 { get; set; }
        public string MinTorqueT4 { get; set; }
        public string MaxTorqueT4 { get; set; }
        public string FinalAngleA4 { get; set; }
        public string TargetAngleA4 { get; set; }
        public string MinAngleA4LL { get; set; }
        public string MaxFinalAngleA4HL { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Commons { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    
        public virtual VehBolt VehBolt { get; set; }
    }
}
