//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehSalesForecast
    {
        public long Id { get; set; }
        public string ForecastCode { get; set; }
        public string ForecastCycle { get; set; }
        public string ForecastWeek { get; set; }
        public string ForecastYear { get; set; }
        public string ForecastMonth { get; set; }
        public Nullable<long> DealerId { get; set; }
        public string PNO { get; set; }
        public Nullable<int> ForecastNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public string UniqueCode { get; set; }
        public string SubmitYearMonth { get; set; }
        public Nullable<long> ForecastCycleId { get; set; }
        public Nullable<long> ForecastWeekId { get; set; }
        public Nullable<long> SubmitYearMonthId { get; set; }
    }
}
