//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehStoreLocationLockConditionView
    {
        public long Id { get; set; }
        public long WarehouseId { get; set; }
        public int LockType { get; set; }
        public string StartCode { get; set; }
        public string EndCode { get; set; }
        public Nullable<long> StorageAreaId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string StorageAreaCode { get; set; }
        public string LockTypeName { get; set; }
    }
}
