//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehSalesForecastUnionGroupByPno12View
    {
        public System.Guid Id { get; set; }
        public string ForecastCycle { get; set; }
        public string SubmitYearMonth { get; set; }
        public string ForecastWeek { get; set; }
        public Nullable<long> DealerId { get; set; }
        public string Pno12 { get; set; }
        public Nullable<int> ForecastNumber { get; set; }
    }
}
