//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehStoreLocationView
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public Nullable<long> LockedBy { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public long StorageAreaId { get; set; }
        public int Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public Nullable<long> DefaultVehicleColorId { get; set; }
        public Nullable<long> DefaultVehicleDisplacementId { get; set; }
        public Nullable<long> DefaultVehicleTypeId { get; set; }
        public Nullable<long> DefaultVehicleConfigurationId { get; set; }
        public Nullable<long> DefaultVehicleOptionsId { get; set; }
        public bool IsTemp { get; set; }
        public bool IsLocked { get; set; }
        public string StorageAreaCode { get; set; }
        public string StorageAreaName { get; set; }
        public long WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public string OemPlaceCode { get; set; }
        public string OemPlaceName { get; set; }
        public string VehicleTypeName { get; set; }
        public string ColorName { get; set; }
        public string DisplacementName { get; set; }
        public string ConfigurationName { get; set; }
        public string OptionsName { get; set; }
        public string IsLockedName { get; set; }
        public string StatusName { get; set; }
        public string IsTempName { get; set; }
    }
}
