//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehSalesForecastTrimView
    {
        public string ForecastCycle { get; set; }
        public Nullable<long> VehicleTypeId { get; set; }
        public Nullable<long> OutTrimType { get; set; }
        public Nullable<long> InnerTrimType { get; set; }
        public string InnerCode { get; set; }
        public string OutCode { get; set; }
        public Nullable<decimal> W01 { get; set; }
        public Nullable<decimal> W02 { get; set; }
        public Nullable<decimal> W03 { get; set; }
        public Nullable<decimal> W04 { get; set; }
        public Nullable<decimal> W05 { get; set; }
        public Nullable<decimal> W06 { get; set; }
        public Nullable<decimal> W07 { get; set; }
        public Nullable<decimal> W08 { get; set; }
        public Nullable<decimal> W09 { get; set; }
        public Nullable<decimal> W10 { get; set; }
        public Nullable<decimal> W11 { get; set; }
        public Nullable<decimal> W12 { get; set; }
        public Nullable<decimal> W13 { get; set; }
        public Nullable<decimal> W14 { get; set; }
        public Nullable<decimal> W15 { get; set; }
        public Nullable<decimal> W16 { get; set; }
        public Nullable<decimal> W17 { get; set; }
        public Nullable<decimal> W18 { get; set; }
        public Nullable<decimal> W19 { get; set; }
        public Nullable<decimal> W20 { get; set; }
        public Nullable<decimal> W21 { get; set; }
        public Nullable<decimal> W22 { get; set; }
        public Nullable<decimal> W23 { get; set; }
        public Nullable<decimal> W24 { get; set; }
        public Nullable<decimal> W25 { get; set; }
        public Nullable<decimal> W26 { get; set; }
        public Nullable<decimal> W27 { get; set; }
        public Nullable<decimal> W28 { get; set; }
        public Nullable<decimal> W29 { get; set; }
        public Nullable<decimal> W30 { get; set; }
        public Nullable<decimal> W31 { get; set; }
        public Nullable<decimal> W32 { get; set; }
        public Nullable<decimal> W33 { get; set; }
        public Nullable<decimal> W34 { get; set; }
        public Nullable<decimal> W35 { get; set; }
        public Nullable<decimal> W36 { get; set; }
        public Nullable<decimal> W37 { get; set; }
        public Nullable<decimal> W38 { get; set; }
        public Nullable<decimal> W39 { get; set; }
        public Nullable<decimal> W40 { get; set; }
        public Nullable<decimal> W41 { get; set; }
        public Nullable<decimal> W42 { get; set; }
        public Nullable<decimal> W43 { get; set; }
        public Nullable<decimal> W44 { get; set; }
        public Nullable<decimal> W45 { get; set; }
        public Nullable<decimal> W46 { get; set; }
        public Nullable<decimal> W47 { get; set; }
        public Nullable<decimal> W48 { get; set; }
        public Nullable<decimal> W49 { get; set; }
        public Nullable<decimal> W50 { get; set; }
        public Nullable<decimal> W51 { get; set; }
        public Nullable<decimal> W52 { get; set; }
        public Nullable<decimal> W53 { get; set; }
        public Nullable<decimal> W54 { get; set; }
        public Nullable<decimal> W55 { get; set; }
        public Nullable<decimal> W56 { get; set; }
        public Nullable<decimal> W57 { get; set; }
        public Nullable<decimal> W58 { get; set; }
        public Nullable<decimal> W59 { get; set; }
        public Nullable<decimal> W60 { get; set; }
        public string VehicleTypeName { get; set; }
        public string ColorName { get; set; }
        public string InnerColor { get; set; }
        public string ForecastWeek { get; set; }
    }
}
