//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehSalesForecastTrimRowsView
    {
        public Nullable<long> OutTrimType { get; set; }
        public Nullable<long> InnerTrimType { get; set; }
        public Nullable<long> VehicleTypeId { get; set; }
        public string ForecastCycle { get; set; }
        public Nullable<int> WeekBelongMonth { get; set; }
        public Nullable<int> ForeNumber { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string VehicleTypeName { get; set; }
        public string ColorName { get; set; }
        public string InnerColor { get; set; }
        public string OutCode { get; set; }
        public string InnerCode { get; set; }
    }
}
