//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehWarehouseView
    {
        public long Id { get; set; }
        public Nullable<long> OemPlaceId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Type { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Comments { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string OemPlaceCode { get; set; }
        public string OemPlaceName { get; set; }
        public string WarehouseStatusName { get; set; }
        public string ShipmentAreaName { get; set; }
        public string ShipmentAreaCode { get; set; }
        public string Tel { get; set; }
        public string Phone { get; set; }
        public string PickPeoplePhone { get; set; }
        public string PickPeopleName { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> ReminderCode { get; set; }
        public string Message { get; set; }
        public string InCarrierBillCode { get; set; }
    }
}
