//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiOData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehXPSCar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehXPSCar()
        {
            this.VehXPSCarFuels = new HashSet<VehXPSCarFuel>();
            this.VehXPSCarObstacles = new HashSet<VehXPSCarObstacle>();
            this.VehXPSCarOptions = new HashSet<VehXPSCarOption>();
            this.VehXPSCarPmls = new HashSet<VehXPSCarPml>();
            this.VehXPSCarWeights = new HashSet<VehXPSCarWeight>();
        }
    
        public long Id { get; set; }
        public string Filler { get; set; }
        public string MainType { get; set; }
        public string ChassisNo { get; set; }
        public string Fyon { get; set; }
        public string BuildingWeek { get; set; }
        public string StructureWeek { get; set; }
        public string PSLAG { get; set; }
        public string TYPNR { get; set; }
        public string Pno34 { get; set; }
        public string FactoryNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Commons { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] DateTimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehXPSCarFuel> VehXPSCarFuels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehXPSCarObstacle> VehXPSCarObstacles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehXPSCarOption> VehXPSCarOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehXPSCarPml> VehXPSCarPmls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehXPSCarWeight> VehXPSCarWeights { get; set; }
    }
}
